playbooks/gophercloud-acceptance-test/run.yaml
And remove the || true, otherwise, the FAIL will be ignored
=> Should use admin to run acceptance test

playbooks/gophercloud-acceptance-test/run.yaml
Enable SUCCESS cases, and add comment to those with failures.
=> Enable the success test cases

playbooks/gophercloud-acceptance-test-mitaka/run.yaml, playbooks/gophercloud-acceptance-test-pike/run.yaml
Use admin to run tests
Remove the |true debug setting
Adjust the test cases
=> Fix the pike/mitaka acc test issue

playbooks/gophercloud-acceptance-test-newton/post.yaml, playbooks/gophercloud-acceptance-test-newton/run.yaml, playbooks/gophercloud-acceptance-test-ocata/post.yaml, playbooks/gophercloud-acceptance-test-ocata/run.yaml, playbooks/terraform-provider-openstack-acceptance-test-newton/post.yaml, playbooks/terraform-provider-openstack-acceptance-test-newton/run.yaml, playbooks/terraform-provider-openstack-acceptance-test-ocata/post.yaml, playbooks/terraform-provider-openstack-acceptance-test-ocata/run.yaml, zuul.d/jobs.yaml
add newton/ocata jobs for gophercloud and terraform provider openstack
=> add newton/ocata jobs for gophercloud and terraform provider openstack

playbooks/gophercloud-unittest/run.yaml, playbooks/init-test/post.yaml, roles/copy-files-on-node/tasks/main.yml, roles/format-test-result-report/tasks/main.yml
use xunit viewer for report page
demo: https://lukejpreston.github.io/xunit-viewer/
=> use xunit viewer for report page

roles/install-devstack/tasks/main.yml
workaround of https://bugs.launchpad.net/devstack/+bug/1745606
=> Install libpcre3-dev manually

playbooks/gophercloud-acceptance-test/run.yaml, playbooks/terraform-provider-openstack-acceptance-test-designate/run.yaml, playbooks/terraform-provider-openstack-acceptance-test/run.yaml, roles/create-devstack-local-conf/defaults/main.yaml, roles/create-devstack-local-conf/tasks/main.yml, roles/install-devstack/defaults/main.yaml, roles/install-devstack/tasks/main.yml, zuul.d/jobs.yaml
- refactor devstack local.conf to populate config according to the openstack version and request services
- refactor devstack installation to keep simple and consistent
=> Refactor devstack local.conf and installation roles 

playbooks/gophercloud-acceptance-test-telefonica/run.yaml, playbooks/terraform-provider-telefonicaopencloud-acceptance-test-telefonica/run.yaml
=> Add OS_VPC_ID environment variable for Telefonica ACC tests

roles/install-golang/tasks/main.yml, zuul.d/jobs.yaml
=> Use custom installation golang first

playbooks/terraform-provider-flexibleengine-acceptance-test-orange/run.yaml, zuul.d/secrets.yaml
=> Add new credentials to Orange

playbooks/terraform-provider-opentelekomcloud-acceptance-test-opentelekomcloud/run.yaml, playbooks/terraform-provider-opentelekomcloud-acceptance-test-telekom/run.yaml, zuul.d/jobs.yaml, zuul.d/secrets.yaml
=> Add job definition for opentelekomcloud provider

roles/create-devstack-local-conf/tasks/main.yml
Add enable service and plugin into local.conf for LBaaS v2
Fixes: #49
=> Add enable service and plugin for LBaaS v2

LICENSE
=> Add copyright file head

playbooks/openstack-cloud-controller-manager-unittest/run.yaml, zuul.d/jobs.yaml, zuul.d/nodesets.yaml
=> UT: dims/openstack-cloud-controller-manager + devstack [in vm]

playbooks/openlab-zuul-jobs-check/inventory, playbooks/openlab-zuul-jobs-check/run.yaml, zuul.d/jobs.yaml, zuul.d/project.yaml
=> Add job for check openlab-zuul-jobs changes

playbooks/terraform-provider-opentelekomcloud-acceptance-test-opentelekomcloud/run.yaml, zuul.d/secrets.yaml
- Add the OS_VPC_ID environment variable
- Change the OS_FLAVOR_ID and OS_FLAVOR_ID_RESIZE value
- Enable all the tests running
- Use an Ubuntu image than cirros image for testing 
- Add OS_AVAILABILITY_ZONE variable
For #63
=> Fix the opentelekomcloud job

playbooks/openstack-cloud-controller-manager-unittest/run.yaml
Change q- enabled services to neutron-
=> Fixes issue #76

roles/create-devstack-local-conf/tasks/main.yml
=> Add commas between service names

roles/create-devstack-local-conf/tasks/main.yml
=> Remove commas between service names

roles/install-devstack/tasks/main.yml
=> Add openstack/manila-tempest-plugin dependency to devstack

playbooks/cloud-provider-openstack-unittest/run.yaml, zuul.d/jobs.yaml, zuul.d/nodesets.yaml, zuul.d/secrets.yaml
Fix #101 
- add nodeset ubuntu-xenial-vexxhost
- add vexxhost credentials
- add job cloud-provider-openstack-unittest
=> Add job cloud-provider-openstack-unittest

playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml, roles/collect-k8s-logs/tasks/main.yaml, roles/install-k8s-jobs-dependences/tasks/main.yaml, zuul.d/jobs.yaml
For # theopenlab/openlab/issues/31
For # theopenlab/openlab/issues/30
=> Add job definition about K8S+keystone authentication+authorization scenario

zuul.d/jobs.yaml
=> Add Queens job define for gophercloud and terraform

playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test/pre.yaml, zuul.d/jobs.yaml
Closes #99 
- add base job cloud-provider-openstack-acceptance-test
- add test job cloud-provider-openstack-acceptance-test-k8s-cinder
=> Add job cloud-provider-openstack-acceptance-test-k8s-cinder

zuul.d/secrets.yaml
=> Regenerate vexxhost credentials with extra newline stripped

playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml, playbooks/cloud-provider-openstack-unittest/run.yaml, zuul.d/jobs.yaml
=> Use export-vexxhost-openrc role in related jobs

playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml
We need to set the hostname and ip to what's known to the openstack environment
=> Update host name and ip address for better e2e testing

playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml, roles/export-vexxhost-openrc/tasks/main.yaml, zuul.d/jobs.yaml
=> Refactor k8s auth job

zuul.d/jobs.yaml
Partial-Bug: kubernetes/cloud-provider-openstack#103
=> Replace "latest-version" by explicit version for e2e job

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml, zuul.d/jobs.yaml
=> Add job k8s-csi-cinder

playbooks/gophercloud-acceptance-test/run.yaml, roles/create-devstack-local-conf/tasks/main.yml
Reverts theopenlab/openlab-zuul-jobs#142
=> Revert "Support enabling Zun on devstack"

playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml
=> Use role to export openrc in k8s cinder in-tree job

playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml, roles/install-k8s/tasks/main.yaml
- Disable iptables parameter in docker service
- Ignore error if deleting taint failed
=> Disable iptables parameter in docker service

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/run.yaml
=> Enlarge timeout of checking test whether successful or not to enhance stability

playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
Reverts theopenlab/openlab-zuul-jobs#163
=> Revert "Fixes issue #162"

roles/install-golang/defaults/main.yml
=> Update golang version requested by k8s

playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
Signed-off-by: Melvin Hillsman <codebauss@gmail.com>
=> Set use-octavia to true

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-flexvolume-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test/pre.yaml, playbooks/cloud-provider-openstack-unittest-nested/run.yaml, playbooks/cloud-provider-openstack-unittest/run.yaml, playbooks/gophercloud-acceptance-test-telefonica/run.yaml, playbooks/gophercloud-acceptance-test/run.yaml, playbooks/gophercloud-unittest/run.yaml, playbooks/openlab-zuul-jobs-check/run.yaml, playbooks/terraform-provider-flexibleengine-acceptance-test-orange/run.yaml, playbooks/terraform-provider-openstack-acceptance-test-designate/run.yaml, playbooks/terraform-provider-openstack-acceptance-test-fwaas/run.yaml, playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml, playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml, playbooks/terraform-provider-openstack-acceptance-test/run.yaml, playbooks/terraform-provider-openstack-unittest/run.yaml, playbooks/terraform-provider-opentelekomcloud-acceptance-test-opentelekomcloud/run.yaml, playbooks/terraform-provider-telefonicaopencloud-acceptance-test-telefonica/run.yaml, roles/create-virtual-machine/tasks/main.yml, roles/install-devstack/tasks/main.yml, roles/install-k8s/tasks/main.yaml
- Add specific name attribue for all of task
- Replace OS_TENANT_* to OS_PROJECT_*
- Use consist way to get API_HOST_IP
Closes theopenlab/openlab#52
=> Do refactor for Ansible jobs to keep struct consistent

playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
This change also enlarge the waitng time of lbaas service deployment.
=> Change the lbaas resource cleanup to use OSC command

playbooks/gophercloud-acceptance-test/run.yaml, roles/install-devstack/tasks/main.yml
Reverts theopenlab/openlab-zuul-jobs#159
=> Revert "Enable Octavia in gophercloud jobs"

playbooks/cloud-provider-openstack-acceptance-test/pre.yaml
=> Rename github.com to k8s.io

playbooks/cloud-provider-openstack-acceptance-test/pre.yaml
Reverts theopenlab/openlab-zuul-jobs#172
=> Revert "Rename github.com to k8s.io"

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-flexvolume-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test/pre.yaml, playbooks/cloud-provider-openstack-test/pre.yaml, playbooks/cloud-provider-openstack-unittest/run.yaml, zuul.d/jobs.yaml
=> Put kubernetes/cloud-provider-openstack source code into k8s.io directory to align with official guidance

roles/install-k8s/tasks/main.yaml
=> Remove zuul.project.src_dir in role install-k8s

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
=> Run kubetest under kubernetes root directory

roles/create-devstack-local-conf/tasks/main.yml
Reverts theopenlab/openlab-zuul-jobs#187
=> Revert "Disable neutron-lbaas plugin"

playbooks/cloud-provider-openstack-test/post.yaml, zuul.d/jobs.yaml
=> Clean volume resource after k8s jobs finished to avoid volume quota error

playbooks/cloud-provider-openstack-format/run.yaml, zuul.d/pipelines.yaml
Forgot to add `cloud-provider-openstack-format` into pipeline, which was introduced in #200 
cc @dims
=> add missing pipeline cloud-provider-openstack-format

playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml
The OpenStack CLI supports doing cascading deletes directly so avoid a bunch of loops and delete directly.
=> Using cascading delete

playbooks/base/pre.yaml
This role will sync the new PR code changes from zuul exector git repo
to the execution node workspace.
=> Add the missed mirror-workspace-git-repos role in pre.yaml of base job

zuul.d/nodesets.yaml
=> Add arm64 nodeset

zuul.d/pipelines.yaml
Periodic jobs will run at UTC-0 0:00, 8:00 and 16:00
=> Make periodic jobs running 3 times everyday

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml, zuul.d/secrets.yaml
- Add encrypted google cloud account info
- Update log uploading script to apply new logic
Close theopenlab/openlab#64
=> Add account login for k8s conformance log uploading

zuul.d/jobs.yaml
Related-Issue: theopenlab/openlab#64
=> Add secrets refer for k8s conformance jobs

zuul.d/secrets.yaml
Related-Issue: theopenlab/openlab#64
=> Update K8S conformance test log secret

roles/create-devstack-local-conf/tasks/main.yml, roles/install-devstack/tasks/main.yml
- Zun do not have release before Pike
- Need to add python-zunclient in PROJECTS environment vars for devstack
=> Fix devstack installation in N, O, P due to Zun project

roles/create-devstack-local-conf/tasks/main.yml
=> Fix neutron-lbaas service launching error

playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
Missing install-k8s role causing job failures
=> Add install-k8s role

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml, zuul.d/secrets.yaml
Closes https://github.com/kubernetes/cloud-provider-openstack/issues/144
=> Add a task to build/push images

zuul.d/secrets.yaml
Pushing images to dockerhub failing due to incorrect
username/password combination. Could possibly be bad
format in secrets file so this updates format and data.
=> Update dockerhub secret data

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
=> Workaround for issue 251

playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml
Related-Bug: theopenlab/openlab#69
=> Only enable Octavia in terraform lbaas tests

roles/create-devstack-local-conf/tasks/main.yml
Related-Bug: theopenlab/openlab#69
=> Add OCTAVIA_MGMT_SUBNET_START and END

zuul.d/secrets.yaml
=> Update OTC Orange TLF secrets.yaml

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
This reverts commit af062c042d588828eaf0dc371e0a867860319429.
Since https://github.com/kubernetes/cloud-provider-openstack/issues/217 is closed
=> Revert "Workaround for issue 251 (#252)"

playbooks/ansible-functional-public-clouds/run.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
Close https://github.com/theopenlab/openlab/issues/71
=> Add support for running ansible fuctional tests against opentelekomcloud and orange clouds

zuul.d/projects.yaml
=> Only run periodic jobs on master branch for packer

playbooks/packer-functional-devstack/run.yaml, roles/create-devstack-local-conf/tasks/main.yml
=> Workaround for q-* and neutron-* in old devstack release

playbooks/packer-functional-devstack/run.yaml
=> Fix packer jobs error caused by image and sg id

playbooks/ansible-functional-public-clouds/run.yaml, playbooks/packer-functional-public-clouds/run.yaml
The glanceclient issue has been fixed in upstream
=> Remove the workaround of glanceclient issue for jobs against public clouds

playbooks/docker-machine-functional-devstack/run.yaml, playbooks/docker-machine-functional-public-clouds/run.yaml
=> Add --debug option for docker-machine for tracing issue

playbooks/osb-checker-test-huaweicloud/run.yaml
Related-Bugs: theopenlab/openlab#75
=> Fix huaweicloud open service broker test error

zuul.d/jobs.yaml, zuul.d/projects.yaml
Github APP is not installed into offical ansible project yet,
avoid to hit Github API rate limits, config openlab forked ansible.
=> Use theopenlab/ansible instead of ansible/ansible

zuul.d/jobs.yaml, zuul.d/projects.yaml
Related-Bugs: theopenlab/openlab#75
=> Trigger osb-checker job manually

playbooks/docker-machine-functional-devstack/run.yaml, playbooks/docker-machine-functional-public-clouds/run.yaml
See:
https://github.com/docker/machine/pull/4543#event-1856397674
https://github.com/docker/machine/pull/4545#event-1856371017
=> Remove docke-machine workaround as Fix PRs have been merged

zuul.d/secrets.yaml
=> Update secrets.yaml for TLF and HuaweiCloud

zuul.d/jobs.yaml, zuul.d/pipelines.yaml
Change-Id: I1caa6327ab975ec9fa016e8f02570e223221c3c3
=> Add a Zuul job for tracking Kubernetes v1.12 branch

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml, zuul.d/secrets.yaml
=> Resolve dockerhub credentials leak

roles/move-k8s-repo-to-k8s-specific-dir/tasks/main.yaml
Related-Bugs: theopenlab/openlab#88
=> Fix if issue in keyword contain case

playbooks/manageiq-providers-openstack-test-devstack/run.yaml, roles/clean-devstack-default-resources/tasks/main.yaml, roles/create-devstack-local-conf/tasks/main.yml, roles/install-devstack/tasks/main.yml, zuul.d/jobs.yaml, zuul.d/projects.yaml
For #theopenlab/openlab/issues/81
=> Add manageiq-providers-openstack-devstack test job

playbooks/manageiq-providers-openstack-test-devstack/run.yaml, roles/clean-devstack-default-resources/tasks/main.yaml
Closes: #theopenlab/openlab/issues/91
=> Fix default devstack resources cleanup of manageiq job

playbooks/manageiq-providers-openstack-test-devstack/run.yaml, playbooks/manageiq-providers-openstack-test-public-clouds/run.yaml
- Fix timeout issue, port 433=>443
- Add some comments for readability
Related-Bugs: theopenlab/openlab#97 theopenlab/openlab#81
=> Fix manageiq-providers-openstack-test-public-clouds timeout issue

roles/format-golang-test-results/defaults/main.yaml, roles/format-golang-test-results/tasks/main.yml, tools/README.md, tools/nosetests.xslt
- Use tebeka/go2xunit to instead of theopenlab/go2xunit
- Build file `nosetests.xslt` into jobs
Related-Bugs: theopenlab/openlab#100
=> Use upstream go2xunit to instead of OpenLab forked

roles/format-golang-test-results/tasks/main.yml
Related-Bugs: theopenlab/openlab#100
=> Fix nosetests.xslt file path issue

playbooks/manageiq-providers-openstack-test-devstack/run.yaml, roles/clean-devstack-default-resources/tasks/main.yaml, roles/create-devstack-local-conf/tasks/main.yml
There are are some packages need to be installed for specific Ubuntu 14.04, this PR add two tasks for specific Ubuntu14.04 and Ubuntu16.04. This PR also fix the neutronclient CLI commands of master of Devstack.
Related-Bug: theopenlab/openlab#101
Related-Bug: theopenlab/openlab#81
=> Fix manageiq job against Mitaka devstack

roles/clean-devstack-default-resources/tasks/main.yaml
Closes: theopenlab/openlab#101
=> Improve resource cleanup of manageiq job to use OSC since O release

zuul.d/secrets.yaml
OpenTelekomCloud account password should be updated in a periodic time,
so we should updated configuration in OpenLab side too.
Closes: theopenlab/openlab#131
=> Update OTC account password in secrets.yaml

playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/post.yaml, playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml, roles/export-cloud-openrc/tasks/main.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml, zuul.d/secrets.yaml
This change add the job of terraform-provider-huaweicloud-acceptance-test-fusioncloud
Close: theopenlab/openlab#130
=> Add terraform-provider-huaweicloud-acceptance-test-fusioncloud job

playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/post.yaml, playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
- Use network "DemoCenter_extenalNet"
- add resource cleanup keyword
=> Clean up terraform fusioncloud jobs resource

roles/export-cloud-openrc/tasks/main.yaml
Closes-Bug: #theopenlab/openlab#140
=> Disable log message of the fusioncloud account info

playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
=> Enable S3 test cases in fusioncloud job

playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
=> Apply AS enabled flavor in FusionCloud job

zuul.d/jobs.yaml
```yaml
irrelevant-files:
- docs/.*
- .*\.md
- OWNERS
- SECURITY_CONTACTS
```
Fixes: kubernetes/cloud-provider-openstack#400
=> Do not run jobs for changes to documentation

zuul.d/pipelines.yaml, zuul.d/projects.yaml
=> Change the time of trigger of openshift + public clouds job

playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
=> Disable AK/SK auth to use token auth instead in FC

roles/config-packer/defaults/main.yaml, roles/config-packer/tasks/main.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
Use the newest release v1.3.3 of Packer to run jobs
Closes: theopenlab/openlab#156
=> Change to run Packer jobs on v1.3.3

playbooks/docker-machine-functional-devstack/run.yaml
- Add OS_USER_DOMAIN_ID and OS_PROJECT_DOMAIN_ID for Mitaka jobs
- Change the AUTH_URL by adding '/v3' postfix for M+ jobs
Closes: theopenlab/openlab#160
=> Fix issues of docker machine + Devstack jobs

playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/post.yaml
Add script to clean up loadbalancer for
terraform-provider-huaweicloud-acceptance-test-fusioncloud
job.
Closes: theopenlab/openlab#167
=> Clean up loadbalancer for fusioncloud job

zuul.d/projects.yaml
Related: # theopenlab/openlab#178
=> Temporarily disable openshift job because of resource cleanup failure

playbooks/ansible-functional-public-clouds/run.yaml, playbooks/bosh-huaweicloud-cpi-release-acceptance-test-huaweicloud/post.yaml, playbooks/openshift-origin-functional-test-public-clouds/cluster-testing.yaml, roles/config-ruby/tasks/main.yaml, roles/create-devstack-local-conf/tasks/main.yml, roles/install-devstack/tasks/main.yml
Fix ansible-lint 601/306 errors.
=> Fix ansible-lint 601/306 error

roles/create-single-k8s-cluster-with-kubeadm/tasks/main.yml, roles/install-docker-ce/tasks/main.yml
Add a role to create k8s master cluster by kubeadm.
Closes: theopenlab/openlab#175
=> Create k8s master cluster by kubeadm

playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml, roles/create-devstack-local-conf/tasks/main.yml
Related-Bug: theopenlab/openlab#183
=> Fix trove deployment failing

roles/install-devstack/tasks/main.yml
Related-Bug: theopenlab/openlab#183
=> Fix devstack trove deployment failling

roles/create-devstack-local-conf/tasks/main.yml
Related-Bug: theopenlab/openlab#183
=> Fix devstack trove deployment failing

zuul.d/jobs.yaml, zuul.d/pipelines.yaml
=> Update the pipeline and jobs to add 1.13 K8s

zuul.d/jobs.yaml, zuul.d/pipelines.yaml
=> Update the pipeline and jobs to add 1.14 K8s

playbooks/spark-integration-test-kubeadm-k8s/post.yaml, playbooks/spark-integration-test-minikube-k8s/post.yaml, roles/create-single-k8s-cluster-with-minikube/tasks/main.yml, zuul.d/jobs.yaml
Closes-Bug: theopenlab/openlab#210
=> Add support for collecting logs of Spark+K8s jobs

zuul.d/secrets.yaml
Related-Bug: theopenlab/openlab#214
=> Update private key and know host of logs.openlabtesting.org

zuul.d/pipelines.yaml
Change periodic time to "30 4,7,16 * * *".
=> Change periodic time

zuul.d/secrets.yaml
Use domain OTC00000000001000010507 instead for
otc cloud.
Closes: theopenlab/openlab#219
=> Switch otc domain

zuul.d/secrets.yaml
Switch to use otc XXXXX10507 account, and to update
infos into secrets.yaml.
Closes: theopenlab/openlab#219
=> Update otc account info

zuul.d/nodesets.yaml
This patch add a new nodeset for gpu resource type.
Related-Bug: theopenlab/openlab#197
=> Add GPU nodeset

zuul.d/jobs.yaml
Related-Bug: theopenlab/openlab#214
=> Try to change attempts to 2

README.md
- Add version option
- Add kubernetes backend example
Related-Bug: theopenlab/openlab#188
=> Update jobs naming notations

zuul.d/pipelines.yaml, zuul.d/projects.yaml
Add some periodic pipelines to trigger jobs on time, split all of jobs
into different piptline to decrease OpenLab resource usage.
Related-Bug: theopenlab/openlab#173
=> Refactor for periodic pipeline and job

playbooks/labkeeper-allinone-deployment-test/run.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
Related: # theopenlab/openlab#217
=> Add a job for checking labkeeper deployment(allinone)

playbooks/kind-integration-test-arm64/run.yaml, roles/install-docker-ce/defaults/main.yaml, roles/install-docker-ce/tasks/main.yml, zuul.d/projects.yaml
Fix Kind job and related roles
Related: theopenlab/openlab#230
=> Fix Kind job and related roles

playbooks/kind-integration-test-arm64/run.yaml
fix param pass
Related-Bug: theopenlab/openlab#230
=> fix param pass

playbooks/ai-on-openlab/run.yaml, roles/create-ai-environment/tasks/main.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml, zuul.d/secrets.yaml
This patch added the job for machine learning test. The new job will be triggered by MOO(https://github.com/moo-ai/moo-ai.github.io) project. You can get more info about
MOO via the [page](https://moo-ai.github.io/index.html)
GPU support will be added later once openlab has GPU resource pool
Related-Bug: theopenlab/openlab#197
=> Add job for machine learning test (CPU part)

playbooks/kind-integration-test-arm64/run.yaml, roles/config-golang/defaults/main.yml
Make golang work with arm64
Related-Bug: theopenlab/openlab#230
=> Make config-golang work with arm64

roles/create-ai-environment/tasks/main.yaml
Use https for ai job to follow CORS rule
=> Use https for ai job

roles/create-ai-environment/tasks/main.yaml
This patch adds an new dataset emnist into AI training scenario. Also
need to change some logics in zuul jobs.
=> Support EMNIST AI training for charactors

playbooks/spark-integration-test-kubeadm-k8s/run.yaml, playbooks/spark-integration-test-minikube-k8s/run.yaml, zuul.d/jobs.yaml, zuul.d/secrets.yaml
Now the spark + k8s jobs need to push docker images to dockerhub, we
have add a docker hub account: theopenlabtesting for openlab jobs common
usages.
Closes #theopenlab/openlab#244
=> The spark jobs require login dockerhub to push docker images

playbooks/spark-integration-test-kubeadm-k8s/run.yaml, playbooks/spark-integration-test-minikube-k8s/run.yaml, zuul.d/secrets.yaml
- Change the dockerhub password and do not log it
- Do not run the tests with 'minikube' in the spark + kubeadm job
Related: #theopenlab/openlab#244
=> Fix the Spark + k8s jobs

playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/kf-tfbenchmarks.yaml.j2, playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/kubeflow_tfbenchmarks.yaml, playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/post.yaml, playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/run.yaml, playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/vc-tfbenchmarks.yaml.j2, playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/volcano_tfbenchmarks.yaml, roles/create-multinodes-k8s-cluster-with-kubeadm/defaults/main.yaml, roles/create-multinodes-k8s-cluster-with-kubeadm/tasks/main.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
This change added a job for running the tensorflow benchmarks on
kubeflow + k8s 1.14 or volcano 0.5.0 +k8s 1.14
implement: #theopenlab/openlab#256
=> Add job for running tensorflow benchmarks with kubeflow/volcano on k8s

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Reverts theopenlab/openlab-zuul-jobs#515, not fixing the failure
=> Revert "workaround to fix cpo e2e job"

playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/kubeflow_tfbenchmarks.yaml, playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/volcano_tfbenchmarks.yaml, zuul.d/jobs.yaml
- Change the docker image to make volcano record job start time and end
time
- Change the timeout of job because it now do not need that long time any more
- Use volcano 0.1 release than master code
=> Change the volcano docker image and fix some nit

playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/kubeflow_tfbenchmarks.yaml, playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/volcano_tfbenchmarks.yaml
Closes: theopenlab/openlab#268
=> Support collecting volcano and kubeflow system components' logs

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Need to determine when the job exhausts memory
=> Add temporary logging of system memory

zuul.d/projects.yaml
Run periodic jobs against with openstack stable branches
for gophercloud, terraform-provier-openstack and rust.
Closes: theopenlab/openlab#267
=> Run periodic jobs against with openstack stable branches

playbooks/kind-integration-test-arm64/run.yaml
Fix KinD on ARM job according to:
https://github.com/kubernetes-sigs/kind/issues/532
Related-Bug: theopenlab/openlab#269
=> Fix KinD on ARM job

zuul.d/jobs.yaml, zuul.d/projects.yaml
Related-Bug: theopenlab/openlab#270
=> Use Ansible jobs to verify new job inherit

playbooks/kind-integration-test-arm64/run.yaml
Fix kind base image entrypoint access rule
Related-Bug: theopenlab/openlab#269
=> Fix kind base image entrypoint access rule

roles/export-kind-gcp-account/tasks/main.yaml
=> Relax kind log for debuging

playbooks/kind-integration-test-arm64/post.yaml, zuul.d/jobs.yaml
Should pass k8s_log_dir to kind job
=> Should pass k8s_log_dir to kind job

playbooks/kind-integration-test-arm64/run.yaml
=> Change log dir

playbooks/kind-integration-test-arm64/run.yaml
=> Copy junit*.xml to log_dir for kind

playbooks/kind-integration-test-arm64/run.yaml
=> Use tee for better debug

playbooks/kind-integration-test-arm64/run.yaml
=> Fix tee using -a to ammend

zuul.d/jobs.yaml, zuul.d/projects.yaml
Refactor jobs using inheritance structure and
try to reuse ansible playbook to support multiple
different testing cases.
Related: theopenlab/openlab#270
Related: theopenlab/openlab#291
=> Refactor jobs using inheritance structure

zuul.d/jobs.yaml, zuul.d/projects.yaml
Add tags for jobs to setting metadata infos.
Related: theopenlab/openlab#264
Related: theopenlab/openlab#291
=> Set tags for openlab jobs

playbooks/manageiq-providers-openstack-test-devstack/run.yaml, zuul.d/jobs.yaml
Manageiq requires postgresql version 10.
Related-Bug: theopenlab/openlab#246
=> Install postgresql 10 for manageiq job

roles/install-openjdk/tasks/main.yaml
Perform apt-get update before install
=> Perform apt-get update before install

playbooks/cluster-api-provider-openstack-image-build/run.yaml, zuul.d/secrets.yaml
1. The encrypt dockerhub user/password is wrong. It should not contain \n. Otherwise 401 error will be raised.
2. The image build job's pipline is changed to `periodic-10/22`.
3. Correct jinjia format.
Close: theopenlab/openlab#301
=> Fix Cloud-Provider-OpenStack job error

roles/create-devstack-local-conf/tasks/main.yml
Fix syntax error: unexpected end of file
Related-Bug: theopenlab/openlab#304
=> Fix syntax error: unexpected end of file

playbooks/hbase-arm-build/run.yaml, roles/install-maven/defaults/main.yaml, roles/install-maven/tasks/main.yaml, roles/install-openjdk/tasks/main.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
This PR add a new hbase periodic job at UTC 10:00
Related-Bug: theopenlab/openlab#300
=> Add hbase periodic build job

zuul.d/jobs.yaml, zuul.d/pipelines.yaml, zuul.d/projects.yaml
Add v1.15 job definition  for cloud-provider-openstack release v1.15
=> Add v1.15 job definition

playbooks/hive-build-arm64/run.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
Implement: theopenlab/openlab#303
=> Add job support run Apache Hive building on ARM64 server

playbooks/kind-integration-test-arm64/run.yaml
Add dump to e2e.sh to fix post failure
=> Add dump to e2e.sh to fix post failure

playbooks/spark-integration-test-minikube-k8s/run.yaml
I have tried in all-in-one env, this is OK, lets try.
=> Try to fix spark-minikube-k8s job

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml, playbooks/cloud-provider-openstack-test/post.yaml, playbooks/cloud-provider-openstack-unittest/run.yaml, roles/export-cloud-openrc/tasks/main.yaml, zuul.d/jobs.yaml
The openrc should be updated for citynetwork cloud as well
Related-Bug: theopenlab/openlab#321
=> Add citynetwork openrc

roles/export-cloud-openrc/tasks/main.yaml, zuul.d/secrets.yaml
Add OS_PROJECT_ID which is used by cloud-provider-openstack realted jobs
=> Add project_id env

zuul.d/secrets.yaml
move project_id secret to the right place.
=> Move project_id to correct place

playbooks/kind-integration-test-arm64/run.yaml
=> Use old bazel for kind

playbooks/kind-integration-test-arm64/run.yaml
=> Adjust bazel version to 0.24

playbooks/kind-integration-test-arm64/run.yaml
=> Bump bazel to 0.23

roles/prepare-workspace/tasks/main.yml
Update /etc/hosts to void error message print
=> Add hostname to etc/hosts

playbooks/init-test/pre.yaml, roles/prepare-workspace/tasks/main.yml
Add root permission for prepare-task
=> Add root permission for prepare-task

playbooks/kind-integration-test-arm64/post.yaml
Upgrade to pyton3.6 for kind post job
=> Upgrade to pyton3.6 for kind post job

playbooks/kind-integration-test-arm64/run.yaml
Add bazel 0.23.2 role in kind job.
related: https://github.com/theopenlab/openlab/issues/340
=> Add bazel 0.23.2 role in kind job.

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Setting env variable as mentioned here
https://github.com/kubernetes/test-infra/issues/14164#issuecomment-527619838
=> fix conformance jobs cpo

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
go get kubetest in not installing succesfully from
$GOPATH/k8s.io/src/cloud-provider-openstack
need to run it from non repo
=> fix cpo jobs

zuul.d/jobs.yaml
k8s 1.16 updated etcd to v3.3.15
=> update etcd version to 3.3.15 for master conformance

playbooks/spark-unit-test-arm64/run.yaml
This refactor spark arm job with changes:
1. pass '-B -e' options of mvn cmd to make the logs more clear
2. only build spark once to decrease the time
=> Refactor spark arm job

playbooks/spark-unchanged-branch-unit-test/run.yaml
Fix the spark periodic job failed if cmd fail.
=> Fix demo spark periodic job

playbooks/flink-end-to-end-test/run_part1.yaml, playbooks/flink-end-to-end-test/run_part2.yaml, playbooks/flink-end-to-end-test/run_part3.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
=> Add flink e2e periodic job

playbooks/flink-end-to-end-test/run_part1.yaml, playbooks/flink-end-to-end-test/run_part2.yaml, playbooks/flink-end-to-end-test/run_part3.yaml
=> Fix flink periodic job

playbooks/flink-end-to-end-test/run_part3.yaml
=> Fix flink task

playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml, roles/install-k8s/tasks/main.yaml
Fix CI job for CPO, hyperkube removed from ./hack/local-up-cluster.sh
=> Remove hyperkube reference

zuul.d/jobs.yaml, zuul.d/projects.yaml
Gophercloud has released v0.4.0, we switch to
test on it for gophercloud periodic jobs.
=> Switch to gophercloud v0.4.0

playbooks/flink-end-to-end-test/run_part1.yaml, playbooks/flink-end-to-end-test/run_part2.yaml, playbooks/flink-end-to-end-test/run_part3.yaml
=> Fix Flink test

playbooks/openlab-zuul-jobs-check/run.yaml
203 should be ignored, since many java project use tab
=> Ignore ansible lint 203

playbooks/flink-end-to-end-test/run_part1.yaml, playbooks/flink-end-to-end-test/run_part2.yaml, playbooks/flink-end-to-end-test/run_part3.yaml, playbooks/openlab-zuul-jobs-check/run.yaml
maven shade plugin 3.2.1 doesn't work on ARM.
=> Fix Flink e2e test

playbooks/flink-end-to-end-test/run_part1.yaml, playbooks/flink-end-to-end-test/run_part2.yaml, playbooks/flink-end-to-end-test/run_part3.yaml
=> Correct maven shade plugin

playbooks/flink-end-to-end-test/run_part1.yaml, playbooks/flink-end-to-end-test/run_part2.yaml, playbooks/flink-end-to-end-test/run_part3.yaml
flink compile failed on maven-shade-plugin 3.0.0
=> Bump maven-shade-plugin to 3.1.0

playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
The regular expression is not robust. It makes the result unexpected.
This patch make it stronger to fix the issue.
Close: theopenlab/openlab#364
=> Fix cpo keystone job error

playbooks/kind-integration-test-arm64/post.yaml
Kind job has been changed to periodic-6, this script here should also be updated.
=> Update post job for kind to use periodic-6

playbooks/flink-end-to-end-test/post.yaml, playbooks/flink-end-to-end-test/run_part1.yaml, playbooks/flink-end-to-end-test/run_part2.yaml, playbooks/flink-end-to-end-test/run_part3.yaml, zuul.d/jobs.yaml
1. Flinke e2e test now runs well. Remove the ignore_error tag.
2. Save Flink log for debug
=> Update flink e2e test

playbooks/flink-end-to-end-test/post.yaml
xml moudle require lxml package
=> Install lxml

playbooks/flink-end-to-end-test/post.yaml
remote_src should be added if the target is remote.
=> Add remote_src

playbooks/flink-end-to-end-test/post.yaml
=> Correct the log path

playbooks/cloud-provider-openstack-test/post.yaml
make sure pv exists before clean up the volume.
Close: theopenlab/openlab#368
=> Fix CPO clean up error

zuul.d/jobs.yaml, zuul.d/projects.yaml
This changes:
1. add periodic job to run spark test with hadoop 3.2
2. change periodic time of spark arm jobs
Related-But: theopenlab/openlab#316
=> Run spark master ut test with hadoop 3.2

playbooks/flink-end-to-end-test/build_and_test_core.yaml, playbooks/flink-end-to-end-test/build_and_test_tests.yaml, playbooks/flink-end-to-end-test/common.yaml, playbooks/flink-end-to-end-test/e2e_checkpoints_and_sticky.yaml, playbooks/flink-end-to-end-test/e2e_heavy_and_ha.yaml, playbooks/flink-end-to-end-test/e2e_misc_hadoopfree_and_misc.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
1. Update e2e test name
2. Add unit test job
3. Add a common playbook.
=> Refactor flink cron job

playbooks/cloud-provider-openstack-acceptance-test-csi-manila/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml, roles/create-devstack-local-conf/tasks/main.yml, zuul.d/jobs.yaml, zuul.d/pipelines.yaml
This PR adds a playbook and a job definition for the CSI Manila acceptance test
=> Add csi-manila job

playbooks/hadoop-yarn-unit-test-arm64/run.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
This change add a for building and running unit tests of Hadoop YARN on
ARM64 server
=> Add job for running Hadoop YARN unit tests on ARM64

playbooks/cloud-provider-openstack-e2e-test-csi-cinder/post.yaml, playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml, zuul.d/jobs.yaml, zuul.d/pipelines.yaml
This commit adds new e2e test for csi cinder in cloud-provider-openstack.
=> CPO: Add cloud-provider-openstack-e2e-test-csi-cinder

playbooks/spark-integration-test-minikube-k8s/run.yaml
We have to make R source package for spark k8s test.
Related-Bug: theopenlab/openlab#379
=> Enable SparkR integration test for spark k8s job

playbooks/flink-end-to-end-test/build_and_test_core.yaml, playbooks/flink-end-to-end-test/build_and_test_tests.yaml, playbooks/flink-end-to-end-test/common.yaml, playbooks/flink-end-to-end-test/e2e_checkpoints_and_sticky.yaml, playbooks/flink-end-to-end-test/e2e_heavy_and_ha.yaml, playbooks/flink-end-to-end-test/e2e_misc_hadoopfree_and_misc.yaml
Some test runs under root but some are not. So the frocksdb build sould keep the same.
=> Build frocksdb in different role

playbooks/spark-integration-test-minikube-k8s/run.yaml
Reverts theopenlab/openlab-zuul-jobs#695 File was wrong
=> Revert "Enable SparkR integration test for spark k8s job"

playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
This commit updates e2e test to fix some of the issues.
=> CPO: update e2e test

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml, playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
This commit is to install kubectl binary explictly as needed by
e2e test and also updates the expression for pod status checking.
=> CPO: Update csi tests

roles/install-k8s/defaults/main.yaml, roles/install-k8s/tasks/main.yaml
Hyperkube has been deprecated, see https://github.com/kubernetes/kubernetes/pull/84662
/cc @adisky @ramineni
=> Remove deprecated hyperkube from the make target

playbooks/flink-end-to-end-test/e2e_misc_hadoopfree_and_misc.yaml
The test download kafka from apache. Hack the url
=> Add apache domain hack

zuul.d/jobs.yaml, zuul.d/nodesets.yaml, zuul.d/projects.yaml
Now all tests passed. Start to send result to flink community now.
=> Start send result to flink community

playbooks/flink-end-to-end-test/e2e_misc_hadoopfree_and_misc.yaml, playbooks/flink-end-to-end-test/post.yaml
A fix has been merged into Flink, remove the hack now.
=> Update Flink hack script

playbooks/flink-end-to-end-test/build_and_test_core_and_tests.yaml, playbooks/flink-end-to-end-test/e2e_misc_hadoopfree_and_misc.yaml, playbooks/flink-end-to-end-test/post.yaml
Flink now use huaweicloud singapore region. Remove some useless hack now
=> Remove some hack for Flink

zuul.d/jobs.yaml, zuul.d/nodesets.yaml, zuul.d/projects.yaml
migrate Flink job to huawei singapore node
=> Use huawei as flink arm node

playbooks/flink-end-to-end-test/build_and_test_core_and_tests.yaml, playbooks/flink-end-to-end-test/e2e_checkpoints_and_sticky.yaml, playbooks/flink-end-to-end-test/e2e_container.yaml, playbooks/flink-end-to-end-test/e2e_heavy_and_ha.yaml, playbooks/flink-end-to-end-test/e2e_misc_hadoopfree_and_misc.yaml
Flink now use the new frocksdb.
=> Bump frocksdb version

playbooks/flink-end-to-end-test/build_and_test_core_and_tests.yaml, playbooks/flink-end-to-end-test/build_and_test_kafka_gelly_and_connectors.yaml, playbooks/flink-end-to-end-test/build_and_test_libraies_and_blink_planner.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
1. Add a new unit test job for kafaka_gelly and connectors
2. Improve unit test structure.
=> Improve Flink unit test

zuul.d/jobs.yaml
Related-Bug: theopenlab/openlab#412
=> Switch to use nodeset ubuntu-bionic for terraform jobs

zuul.d/projects.yaml
Remove some periodic jobs for saving X86 resources.
=> Remove some periodic jobs

zuul.d/nodesets.yaml
This kind of nodeset is used by CPO
=> Add ubuntu-bionic-citynetwork nodeset

playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
This PR enables insecure registry to get registered with docker configuration
=> Set insecure registry to docker configuration

playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
Add wait for registry service to get started in migration job
=> wait for registry service to be up

playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
This PR makes some changes to CPO migration job to make it run successfully.
=> CPO: update migration job

playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
Its unable to pull the required images from worker node. This PR adds allow insecure registry configuration on worker nodes as well.
=> CPO: Migration job fix-2

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Closes: https://github.com/theopenlab/openlab/issues/467
=> Upload manila-csi-plugin image to k8scloudprovider dockerhub

playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
As per discussion in
https://github.com/kubernetes/cloud-provider-openstack/pull/934
=> [cpo] Change test-lb-service.sh script path

zuul.d/secrets.yaml
Replace the existing kubeconfig
=> Update kubeconfig secret for the CPO lb job

playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
Fix the bug introduced in #813
=> [CPO] Fix k8s-keystone-auth job

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml, playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
Recent PR
https://github.com/kubernetes/cloud-provider-openstack/pull/910 ,
changed the way it builds the images, this commit is to update
the same in jobs as well.
=> Fix CPO job errors

playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml, playbooks/gpdb-installcheck-world-tests-on-arm64/run.yaml, zuul.d/jobs.yaml, zuul.d/nodesets.yaml, zuul.d/projects.yaml
This test includes:
1. gpdb build and unit test
2. gpdb demo cluster setup
3. exec installcheck-world regresstion tests.
4. introduce ubuntu-bionic-arm64-huaweicloud nodeset.
=> Add gpdb periodic

playbooks/gpdb-installcheck-world-tests-on-arm64/run.yaml
Fix the /etc/hosts to hardcore the /etc/host for making sure the demo cluster can be lauched successful.
=> Fix gpdb test

playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
Avoid using docker manifest with local image repository
=> [CPO][fix job] avoid using docker manifest with local repository

roles/install-k8s/defaults/main.yaml
etcd version required by latest k8s is 3.4.4.
updating the same
=> update etcd version

playbooks/cluster-api-provider-openstack-conformance/run.yaml
@wangxiyuan can you please review/approve/merge. Thx :)
=> cluster api openstack: run tests serial

playbooks/gpdb-installcheck-world-tests-on-arm64/post.yaml, playbooks/gpdb-installcheck-world-tests-on-arm64/run.yaml, zuul.d/jobs.yaml, zuul.d/nodesets.yaml
Fix some issues and use the official image.
=> Update gpdb job to use official image

playbooks/cloud-provider-openstack-sanity-test-csi-cinder/run.yaml, zuul.d/jobs.yaml, zuul.d/pipelines.yaml
This commit adds csi sanity test job for cinder csi plugin
=> CPO: Add csi cinder sanity job

playbooks/flink-end-to-end-test/common.yaml, playbooks/flink-end-to-end-test/e2e_cron_hadoop241.yaml, playbooks/flink-end-to-end-test/e2e_cron_jdk11.yaml, playbooks/flink-end-to-end-test/e2e_cron_scala212.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
Travis is removed from Flink already. Use Azure way instead.
=> Upgrade flink job

playbooks/flink-end-to-end-test/common.yaml, playbooks/flink-end-to-end-test/e2e_cron_jdk11.yaml, playbooks/flink-end-to-end-test/e2e_cron_scala212.yaml
Huaweicloud repo miss some package. Use the official repo instead
=> Do not use huaweicloud repo

playbooks/gpdb-installcheck-world-tests-on-arm64/post.yaml
This patch will collect all the log details, including diffs file and regression files if the build is failure
=> [GPDB]Collect all necessary build fail log details

playbooks/tensorflow-arm-build/run.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
This PR enable the tensorflow daily build task.
=> Enable Tensorflow Periodic task

zuul.d/projects.yaml
Specific the job only runs on master branch.
Move tf from periodic-2 to periodic-0
=> Fix tensorflow and pytorch job definition

playbooks/tensorflow-arm-build/run.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
Add 2.0.0 and 2.1.0 builds for tf whl packages
=> Split tf jobs from different build version

playbooks/tensorflow-arm-build/run.yaml
https://github.com/tensorflow/tensorflow/issues/40688
https://github.com/tensorflow/tensorflow/issues/40742
=> Fix tf build as numpy latest release error

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml, playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml, roles/create-multinodes-k8s-cluster-with-kubeadm/defaults/main.yaml, roles/create-multinodes-k8s-cluster-with-kubeadm/tasks/main.yaml, zuul.d/jobs.yaml
Fixes https://github.com/kubernetes/kubernetes/issues/91739
=> Run CPO conformance test in multinode Kubernetes cluster

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
192.168.0.0/16 conflicts with the CI nodes.
=> [CPO] Fix e2e-conformance job

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml, playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
Fixing the following error raised for CSI related jobs recently:
```
etcd version 3.4.9 or greater required.
```
=> [CPO] Install etcd v3.4.9 for csi jobs

zuul.d/pipelines.yaml
For: https://github.com/theopenlab/openlab/issues/574
=> Adding support for train and ussuri triggers

playbooks/impala-build-test-arm64/run.yaml
=> Fix impala job

playbooks/impala-build-test-arm64/run.yaml
Update job script to adapt impala upstream.
=> Update impala job script to use upstream

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
to debug
https://logs.openlabtesting.org/logs/51/1151/3c7ac3edc75f2ee7814d209699621eb31b694366/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/994aa25/job-output.txt.gz
=> use describe instead of get to get more pods info

playbooks/impala-build-test-arm64/run.yaml
Impala job failed when build kudu, so keep related logs to check.
=> Update run.yaml for impala job

playbooks/kafka-build-test-arm64/run.yaml, zuul.d/jobs.yaml, zuul.d/projects.yaml
Add define the jod for kafka arm ci and run it .
=> Add arm ci for kafka

playbooks/kafka-build-test-arm64/run.yaml
rename the job name for kafka arm ci and rm some unused code
=> Modify the zuul job for kafka arm ci

zuul.d/jobs.yaml, zuul.d/pipelines.yaml, zuul.d/projects.yaml
This PR is to update conformance job to run against latest branches
=> CPO: Update e2e conformance tests to new releases

playbooks/bucardo-unitest/post.yaml, playbooks/bucardo-unitest/pre.yaml, playbooks/bucardo-unitest/run.yaml, zuul.d/jobs.yaml, zuul.d/pipelines.yaml
Including 4 jobs. 3 are x86 test with PG 10,11,12.
The other is arm test with PG 12
All jobs perl version is 5.30
=> Introduce openlab to bucardo

playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml, playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml, playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
This fix the docker_version inject during using install-k8s role
Enable 3 jobs to use customize_docker_version.
=> Fix CPO for the new ubuntu-focal image

roles/install-devstack/tasks/main.yml
Fixes https://github.com/theopenlab/openlab/issues/674
cc @lingxiankong
=> [CPO]: Fix devstack installation

playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
To work around the hostname == ubuntu issue
=> [cinder-csi-acceptance] added hostname /etc/hosts

roles/install-devstack/tasks/main.yml
/assign @bzhaoopenstack @wangxiyuan @jeblair @emonty
See https://bugs.launchpad.net/devstack/+bug/1906322
https://review.opendev.org/c/openstack/devstack/+/765149
=> [all]: fix devstack pip constraints on Ubuntu Focal

playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
Yet another work around for hostname == ubuntu issue.
Hopefully the last for now, slipped through on Friday /o\
=> [cinder-csi-e2e] added hostname to /etc/hosts

zuul.d/projects.yaml
related issue: https://github.com/theopenlab/openlab/issues/684
This PR will be reverted after holidays, will enble the said jobs after the holiday. Due to openlab doesn't have a maintainer during Chinese holiday.
=> [Announcement]Disable ARM specific test jobs during low maintain holidays

zuul.d/projects.yaml
Reverts theopenlab/openlab-zuul-jobs#1112
=> Revert "[Announcement]Disable ARM specific test jobs during low maintain holidays"

playbooks/openlab-zuul-jobs-check/run.yaml
issues: https://github.com/theopenlab/openlab/issues/689
=> Fix openlab check for the newer skiplist towards latest ansible-lint

playbooks/openlab-zuul-jobs-check/run.yaml
Reverts theopenlab/openlab-zuul-jobs#1117
=> Revert "Fix openlab check for the newer skiplist towards latest ansible-lint"

playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml, roles/export-gcp-account/tasks/main.yaml
I am not yet sure what the actual problem is. So I added some debug
points, and ignore errors so that I don't block any jobs.
=> Added debug and ignores to CPO conformance

zuul.d/secrets.yaml
Associated Issue: https://github.com/theopenlab/openlab/issues/691
=> Update CPO GS bucket

playbooks/impala-build-test-arm64/run.yaml
Reverts theopenlab/openlab-zuul-jobs#1127
=> Revert "Update run.yaml"

zuul.d/jobs.yaml, zuul.d/projects.yaml
=> Disable gophercloud

playbooks/openlab-health-check/post.yaml, playbooks/openlab-health-check/pre.yaml, playbooks/openlab-health-check/run.yaml, zuul.d/jobs.yaml, zuul.d/pipelines.yaml
Setup a health check for openlab to verify the online sys is good.
=> Set a health check for openlab

zuul.d/jobs.yaml, zuul.d/nodesets.yaml, zuul.d/pipelines.yaml, zuul.d/projects.yaml
1. Diable jobs contains: tensorflow, mysql, bucardo
2. Disable citynetwork test nodeset.
3. Exchange the switch nodeset for the jobs which use citynetwork
before.
=> Disable orphan jobs and nodeset

playbooks/cloud-provider-openstack-test-occm/run-1.22.yaml, zuul.d/jobs.yaml, zuul.d/nodesets.yaml, zuul.d/pipelines.yaml, zuul.d/projects.yaml
After citynetwork added the openlab support back, we are happy to use citynetwork nodeset again.
=> [CPO] Use citynetwork nodeset

zuul.d/pipelines.yaml
Add new pipelines for the recent versions of OpenStack:
* Victoria
* Wallaby
* Xena
Issue #2253
=> pipelines: add support for newer OpenStack releases
