- playbooks/acceptance-test/pre.yaml
- playbooks/gophercloud-acceptance-test-newton/post.yaml
- playbooks/gophercloud-acceptance-test-ocata/post.yaml
- playbooks/gophercloud-acceptance-test-pike/post.yaml
- playbooks/gophercloud-acceptance-test/post.yaml
- playbooks/gophercloud-unittest/post.yaml
- playbooks/init-test/post.yaml
- playbooks/init-test/pre.yaml
- playbooks/terraform-acceptance-test/post.yaml
- playbooks/terraform-provider-openstack-acceptance-test-mitaka/post.yaml
- playbooks/terraform-provider-openstack-acceptance-test-newton/post.yaml
- playbooks/terraform-provider-openstack-acceptance-test-ocata/post.yaml
- playbooks/terraform-provider-openstack-acceptance-test-pike/post.yaml
- playbooks/terraform-provider-openstack-acceptance-test/post.yaml
- playbooks/terraform-provider-openstack-unittest/post.yaml
- playbooks/terraform-unittest/post.yaml
- zuul.d/jobs.yaml
Using init-test jobs to ensure workspace exist in pre,
and copy log files on node in post.
> Use init-test as all jobs parents

- playbooks/gophercloud-acceptance-test-mitaka/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-mitaka/run.yaml
The default value of OS_IDENTITY_API_VERSION is 2.0 in Mitaka devstack,
but V2.0 API of keystone will be deprecated in the future, test against
V3 API of keystone in jobs to keep it ok.
> Set OS_IDENTITY_API_VERSION=3 in Mitaka jobs

- playbooks/gophercloud-acceptance-test-mitaka/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-mitaka/run.yaml
The default value of OS_AUTH_URL looks like http://localhost:5000/v2.0,
set it point to v3 URL in Mitaka jobs http://localhost:5000/v3
> Set OS_AUTH_URL point to v3 URL in Mitaka jobs

- playbooks/gophercloud-acceptance-test-mitaka/run.yaml
- playbooks/gophercloud-acceptance-test-newton/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-mitaka/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-newton/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-ocata/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-pike/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
We use Keystone V3 API in all the jobs, so OS_DOMAIN_NAME is back
> Add OS_DOMAIN_NAME option for Mitaka jobs

- playbooks/gophercloud-unittest/run.yaml
- playbooks/terraform-provider-flexibleengine-acceptance-test-orange/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-designate/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
- playbooks/terraform-provider-openstack-unittest/run.yaml
- playbooks/terraform-provider-telefonicaopencloud-acceptance-test-telefonica/run.yaml
Currently we have to copy forked project directory to offical
project directory for verifying CI trigger. Add the check to
avoid copy fail when source directory don't exists.
The copy failing maybe happen when we run devstack backend job on specific backend SDK/Tools project, like: http://logs.openlabtesting.org/logs/8/8/c8184f6fb3609bf38ca96736d9cd721e5e16ffb7/check/terraform-provider-openstack-acceptance-test/8cec66e/
> Ensure source directory exists to avoid cp fail

- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
In mitaka the default keystone endpoint is v2 API, we enable v3 API
in test jobs manually, so OS_DOMAIN_NAME should be added into openrc
in order to auth success. In other version(N/O/P) devstack have added
related domain options into openrc.
> Add OS_DOMAIN_NAME into openrc

- roles/create-devstack-local-conf/tasks/main.yml
- roles/install-devstack/tasks/main.yml
Fine tune task names to avoid confusion
> Fine tune task names

- playbooks/gophercloud-acceptance-test/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
Gophercloud pick environment variable OS_DOMAIN_ID and OS_DOMAIN_NAME,
Terraform-openstack-provider pick OS_DOMAIN_ID, OS_USER_DOMAIN_ID,
OS_PROJECT_DOMAIN_ID, OS_DOMAIN_NAME, OS_USER_DOMAIN_NAME,
OS_PROJECT_DOMAIN_NAME, and both ID and Name can't be empty or
specified. So purpose to specify OS_DOMAIN_ID=default in openrc,
that can override the options OS_USER_DOMAIN_ID and
OS_PROJECT_DOMAIN_NAME in the release after Mitaka.
Fixes #24
> Add OS_DOMAIN_ID=default into devstack openrc

- playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml
- roles/create-devstack-local-conf/tasks/main.yml
- zuul.d/jobs.yaml
By default, we deploy OpenStack that include all of the core services
(Nova, Neutron, Cinder, Keystone, Glance, Swift). Some other services
also are used by lots of users, like: designate, trove, LBaaS, Octavia.
Purpose to enable LBaaS + Octavia services, and run related acceptance
tests for terraform-openstack-provider.
Part of https://github.com/orgs/theopenlab/projects/1#card-6800912
Fixes #32
> Support separate LBaaS tests for terraform-openstack-provider

- playbooks/terraform-provider-openstack-acceptance-test-fwaas/run.yaml
- roles/create-devstack-local-conf/tasks/main.yml
- zuul.d/jobs.yaml
Add job defination and Ansible script to deploy FWaaS service,
and run related terraform-openstack-provider acceptance FW tests.
Fixes: #35
Part of https://github.com/orgs/theopenlab/projects/1#card-6800912
> Support separate FWaaS tests for terraform-openstack-provider

- playbooks/terraform-provider-openstack-acceptance-test-fwaas/run.yaml
- roles/create-devstack-local-conf/tasks/main.yml
Some SDK/Tools project still support FWaaS v1, like
terraform-provider-openstack, even if OpenStack FWaaS team have not
added any new feature into v1. OpenLab should support to run tests
against FWaaS both v1 and v2, let SDK/Tools project to choose run which
one.
Fixes: #43
> Support both FWaaS v1 and v2 in OpenLab

- roles/install-devstack/tasks/main.yml
Barbican project should be deployed in LBaaS job, but it is not in
devstack-gate project list, that cause devstack deploying failed.
Fixes: #41
> Add Barbican into project list

- roles/install-devstack/tasks/main.yml
python-barbicanclient should be added into PROJECTS of devstack-gate
in order to support LBaaS and Octavia installation.
Fixes: #41
> Add python-barbicanclient into PROJECTS

- playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml
Set environment variable OS_USE_OCTAVIA=true in LBaaS job to make
terraform knowing the deployment is LBaaS + Octavia.
Fixes: #49
> Enable Octavia in LBaaS test of terraform-openstack-provider

- playbooks/terraform-provider-telefonicaopencloud-acceptance-test-telefonica/run.yaml
1. According to testing, the flavor 1 and flavor 2 cannot be used to create
server in public clouds, we'd better to config to use the c1.medium as the
OS_FLAVOR_ID and c2.medium as the OS_FLAVOR_ID_RESIZE
2. It was proved that volume attaching will fail if we use cirros image for
testing, so we'd better to switch to use an existing Ubuntu image.
For #60
> Modify telefonica job environment variables to fix some issures

- playbooks/openstack-cloud-controller-manager-unittest/run.yaml
> Novaclient's add_floating_ip function is deprecated use neutron client instead

- playbooks/openstack-cloud-controller-manager-unittest/run.yaml
Without this config, the test result will succeed even if it actually has failed test cases.
> Enable pipefail to exit error when test fails

- roles/create-devstack-local-conf/tasks/main.yml
q- services are all still being run even though neutron-
services are being enabled to replace them
> Disable all q- services

- roles/install-devstack/tasks/main.yml
Fix theopenlab/openlab-zuul-jobs#76
When change q-* to neutron-* during devstack installation, SNAT isn't enabled by default which maybe a devstack bug[1], resulting in virtual machine under devstack has no access to the internet, thus could not install package through package management tools, for example apt-get.
This PR adds a rule via iptables to enable SNAT after devstack installation to fix the problem.
[1] https://github.com/openstack-dev/devstack/blob/master/lib/neutron_plugins/services/l3#L135
> Enable SNAT after devstack installation with neutron-* services

- roles/install-golang/defaults/main.yml
Kubernetes need go1.9.1 or later.
> Bump the go version up to 1.10

- zuul.d/jobs.yaml
- zuul.d/nodesets.yaml
Some deprecated job and nodeset define should be marked and clean up,
like:
1. openstack-cloud-controller-manager-unittest
2. ubuntu-xenial-large
Closes #106
> Clean up deprecated job and nodeset define

- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
- authorization mode should fall back to RBAC as last resort. Node should be the first.
- webhook/policy.json has a hard coded project id. patch it up with our project id
- create an k8s-admin role and grant this role to "admin" user.
> Update to latest k8s-keystone-auth implementation

- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
looks like in vexxhost we don't have privileges to create a role, plus the hassle of cleaning up, so just reuse an existing role
> re-use an existing role to avoid creating a new one

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
There's a bunch of things that need to line up for the taint to be
automatically removed by the openstack external cloud controller. We
should have it all lined up now. So let's remove the explicit removal
here. Note that by removing the node taint by hand, we are short
circuiting some of the code in node_controller that is now run inside
the external cloud controller binary. So give that a chance to run:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cloud/node_controller.go#L291
> [e2e] external cloud controller manager should remove node taint

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
at one point we removed these (while testing e2e against old openstack
provider). Now that we are using the new external cloud provider, add
these back.
> [e2e] oops add back hack for rbac rules

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test/pre.yaml
- roles/copy-files-on-node/tasks/main.yml
- roles/install-k8s-jobs-dependences/tasks/main.yaml
- roles/install-k8s/defaults/main.yaml
- roles/install-k8s/tasks/main.yaml
- zuul.d/jobs.yaml
- Create install-k8s role
- Support to specify version of k8s and etcd
- Add new job
cloud-provider-openstack-acceptance-test-e2e-conformance-latest-release
- Skip to copy 0 size test_results.html
- Add placeholder to upload E2E result to testgrid
Partial-Bug: kubernetes/cloud-provider-openstack#103
> Support k8s E2E test against specified k8s version

- zuul.d/jobs.yaml
In Kubernetes/OpenStack integration scenario, we should keep pipeline
name, job name and trigger comment consistence, that build consist user
experience for developer from k8s community, and easy to understand how
to trigger the specific jobs when the job failed.
- branch-v1.10.0 should be just branch-v1.10
Partial-Bug: theopenlab/openlab#46
> Change k8s e2e job v1.10.0 to v1.10

- playbooks/gophercloud-acceptance-test/run.yaml
- roles/create-devstack-local-conf/tasks/main.yml
Gophercloud will add support for OpenStack Zun and it is using
OpenLab for testing. Therefore, we need to enable Zun in
devstack jobs. The original request comes from this PR:
https://github.com/gophercloud/gophercloud/pull/858
> Support enabling Zun on devstack

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- get upload_e2e.py script and install depends
- set +x for kubetest to get clear log
Partial-Bug: kubernetes/cloud-provider-openstack#103
Closes #139
> Upload E2E test result and log to google storage

- playbooks/gophercloud-acceptance-test-telefonica/run.yaml
- playbooks/terraform-provider-flexibleengine-acceptance-test-orange/run.yaml
- playbooks/terraform-provider-opentelekomcloud-acceptance-test-opentelekomcloud/run.yaml
- playbooks/terraform-provider-telefonicaopencloud-acceptance-test-telefonica/run.yaml
- roles/export-opentelekomcloud-openrc/tasks/main.yaml
- roles/export-orange-openrc/tasks/main.yaml
- roles/export-telefonica-openrc/tasks/main.yaml
- roles/export-vexxhost-openrc/tasks/main.yaml
- zuul.d/jobs.yaml
- zuul.d/secrets.yaml
Closes #115 
- extract openrc as roles to avoid security risk
- delete duplicated job definition gophercloud-acceptance-test-telefonica
> Extract openrc as roles to avoid security risk

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test/pre.yaml
Currently we execute make build in pre.yaml of k8s integration jobs to
compile code, but if compile error happen, that cause job test result
fall into RETRY_LIMIT status, that make some confusion, we should move
make build into run.yaml to cause exact FAILURE status.
Closes #151
> Use FAILURE to replace RETRY_LIMIT when compile error happen

- playbooks/cloud-provider-openstack-unittest-nested/run.yaml
- zuul.d/jobs.yaml
- remove openstack-cloud-controller-manager-acceptance-test-* jobs
- rename openstack-cloud-controller-manager-unittest to
cloud-provider-openstack-unittest-nested, mark it Deprecated
Closes theopenlab/openlab#21
> Switch to kubernetes/cloud-provider-openstack

- playbooks/openlab-zuul-jobs-check/run.yaml
This change skip following lint rules for now:
ANSIBLE0006: Using command rather than module
ANSIBLE0012: Commands should not change things if nothing needs doing
ANSIBLE0013: Use shell only when shell functionality is required
Closes #164
> Make ansible-lint check mandatory and enable "all tasks named" rule

- playbooks/gophercloud-acceptance-test/run.yaml
- roles/install-devstack/tasks/main.yml
Gophercloud supports Octavia and it is using OpenLab for testing.
Therefore, we need to enable Octavia in devstack jobs.
https://github.com/theopenlab/openlab-zuul-jobs/issues/143
> Enable Octavia in gophercloud jobs

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test/pre.yaml
- playbooks/cloud-provider-openstack-unittest/run.yaml
Because this changes have been directly pushed to theopenlab/openlab-zuul-jobs. and after checking with PR https://github.com/kubernetes/cloud-provider-openstack/pull/137 by triggering a job, these changes have broken the k8s+openstack jobs.
FYI: http://logs.openlabtesting.org/logs/37/137/e3f16bd76599a973dfedc45f909841901f85828b/cloud-provider-openstack-acceptance-test-standalone-cinder/cloud-provider-openstack-acceptance-test-standalone-cinder/af37529/
> Revert changes from b4b95293554f639faed4cc1a4a48da0f9efa240f

- zuul.d/jobs.yaml
This change can save the ubuntu-xenial-vexxhost node consumption.
> Change cinder standalone jobs to use general ubuntu-xenial node

- playbooks/cloud-provider-openstack-unittest/run.yaml
- zuul.d/jobs.yaml
Seems it is unstable to run k8s unit tests job on OTC cloud.
> Change k8s ut job back to use vexxhost nodes

- playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/run.yaml
Don't need to change any devstack options with customer local conf and
that will always enable neutron which we do not need in this job.
See: http://logs.openlabtesting.org/logs/33/133/cc2d3456b2bdedda93bc54ffd3e79cd1fe3167cf/cloud-provider-openstack-acceptance-test-standalone-cinder/cloud-provider-openstack-acceptance-test-standalone-cinder/b152670/logs/
> Don't need to create customized local conf when running cinder standalone job

- roles/create-devstack-local-conf/tasks/main.yml
Gophercloud job broke on running db migration on neutron-lbaas [1].
However, neutron-lbaas is deprecated so simply removing it should
be fine.
[1] http://logs.openlabtesting.org/logs/27/927/70f04e44e91c14b867c5ead4b8e859b57864213e/check/gophercloud-acceptance-test/8ab8306/
> Disable neutron-lbaas plugin

- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
After checking the job logs for the issue #191, it looks like we need to
add retry menchanism to get Kubernetes services ready before binding
roles.
Fix: #191
> Add retry mechanism to wait Kubernetes services before binding roles

- roles/install-golang/defaults/main.yml
See: http://logs.openlabtesting.org/logs/periodic/github.com/kubernetes/cloud-provider-openstack/master/cloud-provider-openstack-acceptance-test-e2e-conformance/8c9c326/
The Kubernetes need golang version 1.10.2 or greater
> Bump the default golang version to 1.10.2

- playbooks/base/post-logs.yaml
- playbooks/base/post-ssh.yaml
- playbooks/base/pre.yaml
- zuul.d/jobs.yaml
- zuul.d/pipelines.yaml
- zuul.d/secrets.yaml
- Add the "base" job to openlab-zuul-jobs repo to get rid of project-config changes
- Move the "site_logs" secret to openlab-zuul-jobs
- Move pipelines definition from project-config to openlab-zuul-jobs
> Move the pipelines and base job to openlab-zuul-jobs repo

- zuul.d/jobs.yaml
Because the `ansible-playbook --syntax-check` command don't support
--skip-tags for now, see: http://github.com/ansible/ansible/issues/32536
The ansible-linter can support "skip_ansible_lint" taged tasks.
> Skip the playbooks/base for ansible syntax checking

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
- playbooks/cloud-provider-openstack-test/post.yaml
This change to use config driver to get metadata of nodes if config driver supported, then will also try to request from 169.254.169.254 as an alternative.
Fix # theopenlab/openlab/issues/60
> Add support for using config driver to request metadata

- zuul.d/jobs.yaml
- zuul.d/nodesets.yaml
**ubuntu-xenial-otc** nodeset is only used in cloud-provider-openstack nested
vm scenario, no project refer this job **cloud-provider-openstack-unittest-nested**,
so we can deprecate nodeset at first.
Closes: theopenlab/openlab#61
> Deprecated ubuntu-xenial-otc nodeset

- roles/create-devstack-local-conf/tasks/main.yml
- roles/install-devstack/tasks/main.yml
- Cap the pip version to be 9.0.0, because the latest pip 10 cannot uninstall/upgrade the distutils packages
- Do not install Zun in Mitaka installation as the devstack has been broken for Mitaka
- Cap the setuptools to be 38.0.0, because the latest 39 version cannot work with oslo.utils 3.8.0 which is the limitation for Mitaka devstack
Fix # theopenlab/openlab/issues/65
> Fix the Mitaka devstack installation

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- roles/export-gcp-account/tasks/main.yaml
- use "--junit=/path-to/junit*.xml" to upload junit files
- change conformance test timeout from 120m to 150m
- avoid to echo gcp account info
Related-Issue: theopenlab/openlab#64
> Upload multiple junit files to avoid test timeout

- roles/create-devstack-local-conf/tasks/main.yml
Because In Mitaka devstack installation, it cannot handle the neutron-* services, see:
http://logs.openlabtesting.org/logs/13/1013/6978c44eae5d453cc0780d2e684477ae94a33889/recheck-mitaka/gophercloud-acceptance-test-mitaka/c780ab2/
> Do not replace q-* services with neutron-* service in Mitaka

- roles/create-devstack-local-conf/tasks/main.yml
FWaaS do not switch to neutron-* devstack options totally,
we should be use q-* to enable neutron services for it in order
to avoid deploying error. Only add those enable logic into FWaaS v1
and v2 dg-local.conf to avoid impact main config path.
Close theopenlab/openlab#70
> Use q-* to enable neutron when FWaaS enabled

- roles/create-devstack-local-conf/tasks/main.yml
enable neuron-*, then disable neutron-* and enable q-*,
this way do not work for devstack, the final enable_service
list contain both neutron-* and q-* services, that cause deploy
failing, so add some logic to avoid it.
Related-Bug: theopenlab/openlab#70
> Use legacy q-* to enable neutron fwaas

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Export DOCKER_USERNAME and DOCKER_PASSWORD before setting -x and -e to
avoid leaking sensitive data in log files.
@mrhillsman
> Export env variables before setting -x and -e

- roles/create-devstack-local-conf/tasks/main.yml
Default value of OCTAVIA_MGMT_SUBNET is "192.168.0.0/24", but
in some public cloud fixed ip of zuul testing vm also is in same
subnet "192.168.0.0/24", that cause lb agent can not update lb vm
status.
Related-Bug: theopenlab/openlab#69
> Config OCTAVIA_MGMT_SUBNET to avoid IP conflicting

- playbooks/packer-functional-public-clouds/run.yaml
We have to specify AZ to create vm in huaweicloud now,
so update packer job to apply the logic.
> Packer job update for huaweicloud AZ

- playbooks/ansible-functional-devstack/run.yaml
- zuul.d/jobs.yaml
- zuul.d/pipelines.yaml
- zuul.d/projects.yaml
1. add recheck-rocky pipeline.
2. add packer v1.2.5 and M/N/O/P/Q openstack test jobs,
add these into periodic pipeline.
3. add ansible 2.6 and M/N/O/P/Q openstack test jobs,
add these into periodic pipeline.
4. add role create-devstack-local-conf into ansible devstack
job to support mutliple release install.
5. make openlab check job to use UT nodeset.
> Support to test against multi release OpenStack in packer and ansible

- playbooks/docker-machine-functional-public-clouds/run.yaml
- zuul.d/secrets.yaml
- The `OS_AVAILABILITY_ZONE` env will be set in `export-cloud-openrc` in opentelekomcloud, which will cause error in docker machine jobs, this PR unset the variable in docker machine job
- The `auth_url`  of orange cloud in secrets don't include a "/v3" postfix, which will cause error in docker machine testing cases. This PR correct it.
> Unset AZ env and correct the orange auth_url to fix docker machine jobs

- playbooks/ansible-functional-public-clouds/run.yaml
- playbooks/packer-functional-devstack/run.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
1. Disable container test cases for orange, telefonica and huawei cloud.
2. Specified booting volume size and no_security_group option.
3. Add ansible 2.6 jobs for telefonica and huaweicloud into periodic
pipeline.
Depends-On: https://review.openstack.org/#/c/590078/
Close theopenlab/openlab#78
> Fix ansible testing fails

- playbooks/packer-functional-devstack/run.yaml
Packer Tests need the OS_DOMAIN_ID or OS_DOMAIN_NAME env variable set when using v3 identity services.
> Add OS_DOMAIN_ID env for Packer job with Mitaka devstack

- playbooks/cloud-provider-openstack-acceptance-test-manila-provisioner/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-manila-provisioner/run.yaml
- zuul.d/jobs.yaml
- zuul.d/pipelines.yaml
This PR adds an acceptance test for manila-provisioner from kubernetes/cloud-provider-openstack.
The "testing" part of the job is ok, but I bet at least the `roles` section `run.yaml` is incorrect - this is copied from `cloud-provider-openstack-acceptance-test-standalone-cinder`. I'm quite unfamiliar with this CI and I'd be really grateful if somebody could give me an assistance on how to configure the test to run properly for OpenStack Manila with CephFS backend.
> Adds cloud-provider-openstack acceptance job for manila-provisioner

- playbooks/packer-functional-public-clouds/run.yaml
We use "default" security group for packer tests again public clouds,
but "default" is shared sg, rules of "default" sg might be changed by
other, that might cause packer tests failing, so use "openlab-jobs-sg"
in stead of "default".
> Use security group "openlab-jobs-sg" for packer tests

- playbooks/cloud-provider-openstack-acceptance-test-manila-provisioner/run.yaml
Adds `openstack/devstack-plugin-ceph` to `install-devstack`, should fix the error in http://logs.openlabtesting.org/logs/67/267/6d54444f535424f6bdd95cb1ef7e1ed4f933376b/cloud-provider-openstack-acceptance-test-manila-provisioner/cloud-provider-openstack-acceptance-test-manila-provisioner/1e275c1/logs/devstacklog.txt.gz
> manila-provisioner job: add devstack-plugin-ceph

- roles/install-devstack/tasks/main.yml
Version of reno lib is too high in Mitaka devstack deployment.
Closes: theopenlab/openlab#79
> Fix devstack Mitaka deployment failed

- playbooks/cloud-provider-openstack-acceptance-test-manila-provisioner/run.yaml
This PR modifies the list of enabled services in manila-provisioner job. There might be still some left that are not needed but should at least fix the issue where etcd was ran twice (once by k8s and once as a separate service).
> manila-provisioner job: modify enabled services

- roles/install-devstack/tasks/main.yml
Related-Bugs: theopenlab/openlab#79
> apt pruge python-six to install reno

- playbooks/packer-functional-public-clouds/run.yaml
We test packer with flavor t2.micro against Orange cloud,
vm can be launched and active, but guest OS and sshd process
launch slowly, that cause packer check ssh connection timeout.
Closes: theopenlab/openlab#80
> Fix packer-1.2.5-functional-orange failing

- playbooks/cloud-provider-openstack-acceptance-test-manila-provisioner/run.yaml
This PR:
* fixes sourcing of OpenRC params when creating k8s secret
* adds a sleep to wait for ServiceAccount default/default to complete
> manila-provisioner job: fixed sourcing openrc params

- playbooks/docker-machine-functional-public-clouds/run.yaml
The "docker-machine rm" may don't remove the VMs successfully, This PR add
a vm deletion step to ensure cleanup.
> Improve the cleanup of docker-machine job

- playbooks/cluster-api-provider-openstack-image-build/run.yaml
- roles/move-k8s-repo-to-k8s-specific-dir/defaults/main.yaml
- roles/move-k8s-repo-to-k8s-specific-dir/tasks/main.yaml
- zuul.d/jobs.yaml
Job cluster-api-provider-openstack-image-build have to be executed in
sigs.k8s.io directory, so modify role move-k8s-repo-to-k8s-specific-dir
to handle this, and run it on nodeset ubuntu-xenial, add role
install-k8s.
Related-Bugs: theopenlab/openlab#88
> Run cluster-api-provider-openstack-image-build in sigs.k8s.io

- playbooks/docker-machine-functional-public-clouds/run.yaml
Because the `GET v2/{tenant}/servers/` API doesn't support by public clouds, we should ignore the 404 error of "docker-machine ip machine_name".
> Fix resource cleanup of docker-machine job

- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
- roles/create-devstack-local-conf/tasks/main.yml
Gophercloud and terraform-provider-openstack need to test
neutron trunk feature, but trunk extension is not enabled
by default in devstack, so we add a flat "neutron-ext" to
enable "neutron-trunk" or others extenstions.
Related-Bugs: theopenlab/openlab#92
Related-Bugs: theopenlab/openlab-zuul-jobs#341
> Enable neutron-trunk when extension enabled

- roles/create-devstack-local-conf/tasks/main.yml
Add enable_plugin neutron git://git.openstack.org/openstack/neutron
into dg-local.conf so that non-default neutron extension can be enabled
in devstack, like: neutron-trunk
Related-Bugs: theopenlab/openlab#92
> Enable Neutron plugin config in dg-local.conf

- playbooks/docker-machine-functional-public-clouds/run.yaml
- playbooks/packer-functional-public-clouds/run.yaml
PR theopenlab/openlab#345 export OS_DOMAIN_ID and OS_DOMAIN_NAME
into envrionment variables, but packer and docker-machine can not
handle both them existed. This patch address the issue.
Closes: theopenlab/openlab#94
> Fix both OS_DOMAIN_ID and OS_DOMAIN_NAME existed issue

- roles/clean-devstack-default-resources/tasks/main.yaml
- openstackclient don't support --sort-column option in M, N, O, P,
so use more simple command to handle flavor.
- sync with upstream of manageiq-providers-openstack to address
bin/setup issue.
Closes: theopenlab/openlab#95
> Fix manageiq-providers-openstack-test-devstack issues

- playbooks/manageiq-providers-openstack-test-devstack/run.yaml
- playbooks/manageiq-providers-openstack-test-public-clouds/run.yaml
Sometimes ftp.cz.debian.org mirror may be unavailable, we
have faced several times in this week, try to use main site
ftp.debian.org to instead.
Closes: theopenlab/openlab#96
Related-Bugs: theopenlab/openlab#81
> Fix debian mirror unavailable issue

- playbooks/manageiq-providers-openstack-test-public-clouds/run.yaml
public cloud apply SSL connection in API, so we should use SSL way to test integration.
Closes: theopenlab/openlab#97
Related-Bugs: theopenlab/openlab#81
> Enable SSL to test manageiq-providers-openstack-test-public-clouds

- playbooks/docker-machine-functional-devstack/run.yaml
- playbooks/manageiq-providers-openstack-test-devstack/run.yaml
docker-machine don't support OpenStack version discovery,
so enable legacy endpoint format in devstack related jobs.
Related-Bugs: theopenlab/openlab#74
> Enable legacy endpoint format for docker-machine

- README.md
- Add `Getting Started`
- Add `Development Guide`
Related-Bug: theopenlab/openlab#100
> Add document links into README

- playbooks/terraform-provider-flexibleengine-acceptance-test-orange/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-designate/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-fwaas/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
- playbooks/terraform-provider-openstack-unittest/run.yaml
- playbooks/terraform-provider-telefonicaopencloud-acceptance-test-telefonica/run.yaml
For these jobs, we don't need to trigger jobs from the forked repos any
more.
Closes: theopenlab/openlab#123
Related-Bugs: theopenlab/openlab#100
> Clean the legacy Go projects path compatibility workarounds

- zuul.d/projects.yaml
Telefonica Cloud account is disable, disable related jobs in OpenLab
side to avoid confused error happend.
- docker-machine-0.15.0-functional-telefonica
- manageiq-providers-openstack-test-telefonica
- openstacksdk-ansible-stable-2.6-functional-telefonica
- packer-1.2.5-functional-telefonica
Closes: theopenlab/openlab#126
> Disable Telefonica Cloud related jobs

- playbooks/terraform-provider-openstack-acceptance-test-huaweicloud/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-opentelekomcloud/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-orange/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-telefonica/run.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Add jobs to integrate terraform-provider-openstack with
public clouds: telefonica, orange, opentelekomcloud and huaweicloud.
Related-Bug: theopenlab/openlab#125
> Add jobs to integrate terraform-provider-openstack with generic clouds

- roles/config-packer/tasks/main.yaml
- zuul.d/pipelines.yaml
- zuul.d/projects.yaml
1. Use upstream projects to instead of OpenLab forked projects to
avoid syncing with upstream manually.
2. Add UTC-0 04:00 in periodic pipeline in order to have more chance
to trigger periodic jobs and show issue of periodic jobs
Closes: theopenlab/openlab#133
> Clean forked project theopenlab/packer and theopenlab/machine

- playbooks/docker-machine-functional-devstack/run.yaml
- playbooks/docker-machine-functional-public-clouds/run.yaml
- roles/config-docker-machine/tasks/main.yaml
1. Add role "config-docker-machine" to compiled and install
docker-machine from source code.
2. Change job logic in order to putting related code together
3. Fix cp to same path issue, because we have used upstream project,
don't need to cp forked project into official path
Related-Bug: theopenlab/openlab#133
> Do refactor for docker-machine jobs

- zuul.d/projects.yaml
We forget to cleanup hanging resources when test cases failed
in terraform periodic jobs, disable these jobs temporarily to
avoid resource usage touch quota limit.
Related-Bug: theopenlab/openlab#136
> Disable terraform periodic jobs

- roles/install-k8s/defaults/main.yaml
k/k has now moved to 3.3.10 of etcd
https://github.com/kubernetes/kubernetes/pull/71615
Change-Id: I450b3aff33235cc9d0d2abe5290f7c0cdf422f20
> Update to etcd 3.3.10

- playbooks/osb-checker-test-huaweicloud/osb-checker-config-huaweicloud-dcs.json.j2
- playbooks/osb-checker-test-huaweicloud/osb-checker-config-huaweicloud-dms.json.j2
- playbooks/osb-checker-test-huaweicloud/osb-checker-config-huaweicloud-obs.json.j2
- playbooks/osb-checker-test-huaweicloud/osb-checker-config-huaweicloud-rds.json.j2
According to the openservicebroker spec, the 409 conflict status of
provision should only be return when pass different properties and an
existed id.
Closes: theopenlab/openlab#138
> Use different properties and existed id to test confliction cases

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/post.yaml
Image "Rancher TerraformAccTest" is created in job
terraform-provider-huaweicloud-acceptance-test-fusioncloud,
should be cleaned up in post.yaml.
> Cleanup image in terraform fusioncloud job

- playbooks/gophercloud-acceptance-test-telefonica/run.yaml
- playbooks/terraform-provider-flexibleengine-acceptance-test-orange/run.yaml
- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-designate/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-fwaas/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-public-clouds/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
- playbooks/terraform-provider-opentelekomcloud-acceptance-test-opentelekomcloud/run.yaml
- playbooks/terraform-provider-telefonicaopencloud-acceptance-test-telefonica/run.yaml
- zuul.d/projects.yaml
- remove OS_SHARE_NETWORK_ID in terraform and gophercloud jobs
- disable terraform telefornica job
Closes: theopenlab/openlab#139
> Remove OS_SHARE_NETWORK_ID

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
- disable TestAccVpcRouteIdsV2DataSource_basic
- change timeout to 4 hours
> Disable test cases that cause panic

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
TestAccVpcPeeringConnectionV2DataSource_basic,
TestAccVpcRouteIdsV2DataSource_basic, TestAccVpcRouteV2DataSource_basic
will cause golang panic to interrupt test process, so skip theses.
> Skip VPC peering and vpc routes datasource tests

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/post.yaml
- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
- Disable all of S3 test cases
- Cleanup router "terraform_provider_test" and "terraform_provider_test1"
- Rename job "terraform-provider-huaweicloud-v1.2.0-acceptance-test-fusioncloud" to
"terraform-provider-huaweicloud-acceptance-test-fusioncloud"
- Use master terraform-provider-huaweicloud to run tests
- Set timeout to 5 hours to avoid fusioncloud running job broken
> Diable S3 test cases in fusioncloud job

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
Skip the cce, csbs, cts, dms and vbsbackup tests,
these services are not supported in fusioncloud.
> Skip the tests of unsupported services

- zuul.d/pipelines.yaml
- Change periodic jobs trigger time to UTC-0 04:00, 09:00 and 16:00
to avoid fusioncloud long job miss trigger point
> Change periodic jobs trigger time

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
Domain of FusionCloud testing doployment have been applied in
public network, we can remove workaround in FusionCloud job,
something like: "\*.\*.fusioncloud.huawei.com"
> [WIP]Remove domain mapping hosts workaround

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
Use regular flaovr to boot server to avoid falling into special cases.
> Change flavor to boot server in FusionCloud job

- zuul.d/jobs.yaml
Reverts theopenlab/openlab-zuul-jobs#390
Apologies, changes should happen in kubernetes/cloud-provider-openstack .zuul.yaml
> Revert "Do not run jobs for changes to documentation"

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
Because the endpoints of fusioncloud environment have been changed, and
new domain name cannot access directly, so we need to add domain name
mapping again.
> Add domain name mapping for terraform fusioncloud job

- playbooks/openlab-zuul-jobs-check/run.yaml
The newest ansible-lint 4.0.0 has change the command to specify the
skipped rules.
Closes-Bug: #theopenlab/openlab#145
> Modify the jobs-checker job because the newest ansible-lint

- playbooks/osb-checker-test-huaweicloud/run.yaml
As the osb-checker has been refactor, it need also to run `npm install`
under the osb-checker/common directory
Closes-Bug: #theopenlab/openlab#144
> Run npm install under osb-checker/common

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
Enable AKSK configuration, that will impact all of acceptance tests,
all services will try to use AKSK auth first.
> Enable AKSK test cases

- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
Manila acctest failed, but there is no log we can find
the reason, enable OS_DEBUG to get the log details.
Related-Bug: theopenlab/openlab#142
> Enable OS_DEBUG=1 to get the log details

- roles/create-devstack-local-conf/tasks/main.yml
Modify the local.conf to set up Devstack with manila
enabling the LVM driver which operates in
driver_handles_share_services=False mode.
Related-Bug: theopenlab/openlab#142
> Set up Devstack with manila enbaling the LVM driver

- playbooks/openshift-origin-functional-test-public-clouds/cluster-testing.yaml
- playbooks/openshift-origin-functional-test-public-clouds/extra_vars.yml.j2
- playbooks/openshift-origin-functional-test-public-clouds/post.yaml
- playbooks/openshift-origin-functional-test-public-clouds/run.yaml
- zuul.d/jobs.yaml
- zuul.d/pipelines.yaml
- zuul.d/projects.yaml
This change add jobs:
-  openshift-origin-v3.9.0-functional-test-huaweicloud
- openshift-origin-v3.9.0-functional-test-opentelekomcloud
- openshift-origin-v3.9.0-functional-test-telefonica
- openshift-origin-v3.9.0-functional-test-orange
Implement: #theopenlab/openlab#149
> Add jobs of openshift origin + public clouds

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
Use whitelist to filter the acctests running in Fusioncloud.
> Add whitelist of acctests running in Fusioncloud

- playbooks/openshift-origin-functional-test-public-clouds/cluster-testing.yaml
Sometimes the resource cleanup may need to take a longer time.
Related: #theopenlab/openlab#149
> Change the timeout of openshift job from 60s to 180s

- zuul.d/projects.yaml
We trigger manageiq jobs in check-generic-cloud pipeline manually,
actually those jobs don't create any resource for public cloud environment,
so we can put them into periodic pipeline to be triggered automatically,
now we have periodic-2 pipeline run at UTC-0 22:00, that is a good time to
avoid tenant quota limit of public cloud account to run jobs, so plan to move
all of manageiq jobs into it, and we can switch to official project
manageiq/manageiq-providers-openstack in OpenLab configuration.
Close: theopenlab/openlab#152
> Run all of manageiq jobs in periodic-2 pipeline

- playbooks/manageiq-providers-openstack-test-devstack/run.yaml
- playbooks/manageiq-providers-openstack-test-public-clouds/run.yaml
OpenSSL package update that casue ManageIQ jobs failed.
OpenSSL package name is changed, that cause wget failed and
ManageIQ jobs failed. We should use more flexbile way to get package.
Closes: theopenlab/openlab#158
> Fix OpenSSL package downloading error

- roles/config-docker-machine/tasks/main.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Use the newest release v0.16.1 of docker machine to run jobs
Closes: theopenlab/openlab#155
> Change to run docker machine jobs on  v0.16.1

- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Ansible 2.7 version have been released for a time, to support the
new version in OpenLab Ansible jobs, the changes:
1. Remove the version number from job names
2. Modify the version number from 2.6 to 2.7 for descriptions
Close: theopenlab/openlab#154
> Support to intergrate with Ansible stable-2.7

- playbooks/terraform-provider-openstack-acceptance-test-designate/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-fwaas/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-public-clouds/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml
- playbooks/terraform-provider-openstack-acceptance-test/run.yaml
The TF_SCHEMA_PANIC_ON_ERROR flag allows to catch invalid
terraform schema assignments. It would be great if we can
enable this environment flag.
Close: theopenlab/openlab#166
> Enable TF_SCHEMA_PANIC_ON_ERROR for terraform jobs

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/post.yaml
Sometimes secgroup_2 is residue after fusioncloud job
running, clean up it. And also we have to clean up port_2.
Closes: theopenlab/openlab#170
> Clean up secgroup_2 for fusioncloud job

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/post.yaml
Remove subnet from router to make sure we can delete subnet
and router when clean up resources.
Closes: theopenlab/openlab#174
> Remove subnet from router

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
Currently the `cloud-provider-openstack-acceptance-test-csi-cinder` job in https://github.com/kubernetes/cloud-provider-openstack fails (see: https://github.com/kubernetes/cloud-provider-openstack/pull/430 + logs: http://logs.openlabtesting.org/logs/30/430/044b09b3d0d07fcb43a678a9e30c8dfb48c68c97/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/e8e2df9/job-output.txt.gz just search for `Error response from daemon: No such image: quay.io/k8scsi/csi-attacher:canary`)
Running the `make` command like in the Zuul job creates an `csi-attacher:latest` image like defined here: https://github.com/kubernetes-csi/external-attacher/blob/master/release-tools/build.make#L68 probably it would be a good idea to pin the version of the tools (e.g. …
> Adjust csi-attacher name for new release

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
The current sed expression `cloud.conf` was to "greedy" and matched for example also `cloud-config` which leads to an error: http://logs.openlabtesting.org/logs/34/434/175ee1955b3c4ac1741013c9cadb39fbc6117fe4/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/46ea07f/job-output.txt.gz (grep for `error parsing manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml`).
The reason for the failure was the sed expression which matched more than only `cloud.conf:`:
Without the fix:
```bash
sed "s/cloud.conf.*$/cloud.conf: $cloud_cfg/g"  manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml
kind: Secret
apiVersion: v1
metadata:
name: cloud.conf: W0dsb2JhbF0KcmVnaW9uPVJlZ2lvbk9uZQp1c2VybmFtZT1hZG1pbgpwYXNzd29yZD1wYXNzdzByZAphdXRoLXVybD1odHRw …
```
> Correct sed expression to match only cloud.conf in csi e2e test

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-flexvolume-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/run.yaml
Currently, all the cloud-provider-openstack tests use block storage
version v2 which is deprecated. This commit updates to use latest
version v3 instead.
> update cloud-provider-openstack tests to use block storage v3

- playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml
- zuul.d/jobs.yaml
- zuul.d/nodesets.yaml
- OpenStack upstream have used tox to deploy trove in python3,
OpenLab keep to use same way to do it.
- OpenStack CI use 4 vCPUs and 8G RAM instances to run trove integration
tests, OpenLab should be able to use same falvor, so remove nodepool
label `ubuntu-xenial-otc`.
Closes: theopenlab/openlab#183
> Fix devstack trove deploying failed

- playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml
Change directory of trove to {toxinidir} for
testenv trovestack in /trove/tox.ini.
Related-Bug: theopenlab/openlab#183
> Fix error of running trovestack in openlab job

- roles/create-devstack-local-conf/tasks/main.yml
This PR adds the support to enable Ironic on DevStack.
To have ironic enable you need to set `ironic` in `enable_services`
Closes: theopenlab/openlab#195
> Support to enable Ironic on DevStack

- playbooks/terraform-provider-openstack-acceptance-test-trove/run.yaml
Fix trove job errors with several changes:
1. trovestack scripts can not run as root
2. change path of devstack src to /opt/stack/new/devstack
3. change dest path of trove to /opt/stack/new/trove
4. change owner of files in directory of /opt/stack
and /etc/trove to support running tox -etrovestack
5. there is an error of trove upstream when exec tox -etrovestack,
which hard code of /opt/stack/trove/test-upper-constraints.txt
in tox.ini, change it to
{toxinidir}/stack/trove/test-upper-constraints.txt
Closes: theopenlab/openlab#183
> Fix trove job errors

- roles/create-devstack-local-conf/tasks/main.yml
This PR fixes some problems in the generated `local.conf` when Ironic is enabled 
The problems were found while trying to setup in the gophercloud repository, based on the local.conf generated some tests were executed in DevStack  and the following changes are necessary:
- Change `:` to `=` DEFAULT_INSTANCE_TYPE and DEFAULT_INSTANCE_TYPE
- Remove `Q_AGENT` and `Q_ML2_TENANT_NETWORK_TYPE`
- Remove `ansible` from `IRONIC_ENABLED_DEPLOY_INTERFACES`
Closes: theopenlab/openlab#205
> Fix local.conf for Ironic

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
Both variables are in GA (since 1.13/1.12) and no longer required, see: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates. with the Feature gates still provided the test will fail always since the API server doesn't come up: http://logs.openlabtesting.org/logs/20/520/18b453d905868ac448a664b7c897edac4e680532/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/7b6f0b5/logs/kubernetes/kube-apiserver.log
```bash
W0305 06:26:38.152427    9523 feature_gate.go:218] Setting GA feature gate CSIPersistentVolume=true. It will be removed in a future release.
Error: invalid argument "CSIPersistentVolume=true,MountPropagation=true" for "--feature-gates" flag: unrecognized feature gate: MountPropagation
Usage:
hyperkube …
```
> Remove FEATURE_GATES variable

- roles/create-devstack-local-conf/tasks/main.yml
Fix devstack install error if enable designate
There is an error happened when installing devstack enabled designate:
ERROR designate.cmd.pool_manager [-] You have designate-worker enabled, starting designate-pool-manager is incompatible with designate-worker. You need to start designate-worker instead.
Related-Bug: theopenlab/openlab#216
> Remove enable_services of designate devstack conf

- zuul.d/pipelines.yaml
- zuul.d/projects.yaml
There are enough resources to run testing in Orange public cloud
account, like: router and floating ip, that cause test cases always
failed, make no sense to running it until there are more resources.
Disable all of Orange jobs to save execute nodes for OpenLab.
Related-Bug: theopenlab/openlab#214
> Disable Orange jobs

- README.md
Move jobs naming notations to doc site[1] to keep development content together.
Related-Bug: theopenlab/openlab#173
[1]: https://docs.openlabtesting.org/publications/contributors/development-guide#job-naming-notations
> Move jobs naming notations to doc site

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Until a better solution is determined we can check
for the zuul.branch variable to determine whether
we should push images to docker. This will resolve
https://github.com/theopenlab/openlab/issues/223
> Check for branch master before docker push

- roles/create-devstack-local-conf/tasks/main.yml
This patch fixes the issue mentioned in PR#222.
The default size of devstack swift is 2G, if we enable octavia or we
create some new images into glance during test. We will get failure.
The key reason for this is the swift device size is too small. So this
patch will increase the size through pass a env parameter in devstack
local conf.
Close: theopenlab/openlab#222
> Fix PR#222 for increase swift device size

- zuul.d/projects.yaml
Move periodic jobs in following projects back to OpenLab
- gophercloud/gophercloud
- cloudfoundry/bosh-openstack-cpi-release
- kubernetes/cloud-provider-openstack
Related-Bug: theopenlab/openlab#173
> Move outside periodic jobs back to OpenLab

- playbooks/terraform-provider-huaweicloud-acceptance-test-fusioncloud/run.yaml
This removes the default security group workaround as the issue has been addressed on terraform-provider-huaweicloud.
> Remove unneeded workaround for default sg of fusioncloud

- playbooks/helm-integration-test-kubeadm-k8s/run.yaml
- roles/create-single-k8s-cluster-with-kubeadm/defaults/main.yaml
- roles/create-single-k8s-cluster-with-kubeadm/tasks/main.yml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Add two periodic job of helm charts integration test
with k8s v1.14.0 and v1.12.7 versions
We will add two jobs of integration test of helm with native k8s cluster which use latest version chart-testing tool:
1. helm with 2.12.2 and kubernetes with v1.14.0
2. helm with 2.12.2 and kubernetes with v1.12.7
Closes: theopenlab/openlab#212
> Add helm charts integration test with k8s

- roles/create-single-k8s-cluster-with-minikube/defaults/main.yaml
- roles/create-single-k8s-cluster-with-minikube/tasks/main.yml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Add a parameter "kubernetes_version" for
role create-single-k8s-cluster-with-minikube to
support specify k8s version if needed.
Related: theopenlab/openlab#213
> Support kubernetes version for minikube start

- playbooks/kind-integration-test-arm64/run.yaml
Comment out bazel related roles, we use cloud image for KinD test, 
previously the job fails because of bazel installation, the cloud image
uploaded included a successfuly built bazel. lets skip the bazel 
installation and make the job running first. We can refactor the bazel
role latter if required.
Related: theopenlab/openlab#230
> Comment out bazel related roles

- playbooks/base/post-logs.yaml
After https://github.com/theopenlab/openlab/issues/202 merged, we can change this to 'https'.
> change http to https in log link

- playbooks/kind-integration-test-arm64/run.yaml
The timeout is too short for KinD tests according to current test logs:
http://status.openlabtesting.org/builds?job_name=kind-integration-test-arm64
Issue link: https://github.com/theopenlab/openlab/issues/230
> The timeout is too short for KinD tests

- roles/create-ai-environment/tasks/main.yaml
- zuul.d/projects.yaml
This will ignore the CUDA and NVIDIA driver installation when job use
huaweicloud. Now, GPU resources only support Tesla V100 GPU on
huaweicloud with a specific flavor.
Issue link: https://github.com/theopenlab/openlab/issues/196
> [Issue #196]Enable GPU AI job

- roles/config-gcc/defaults/main.yml
- roles/config-gcc/tasks/main.yml
You can use below config to enbale gcc-7:
```
roles:
- role: config-gcc
gcc_version: 7
```
Close-issue: https://github.com/theopenlab/openlab/issues/239
> Add support for config-gcc role

- roles/create-ai-environment/tasks/main.yaml
The inference page now is hosted on log server. Set the model url
to be `logs` so that it can follow http CORS rule
> Fix inference page CORS error

- zuul.d/projects.yaml
- Remove OTC related periodic jobs to save resources
- Disable HuaweiCloud related periodic because of no enough budget
- Reorder periodic jobs to keep consistent output in pipeline
Related-Bug: theopenlab/openlab#173
> Disable and remove public cloud periodic jobs

- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Support acceptance test against OpenStack Stein release in OpenLab
Add periodic jobs for ansible/packer/docker-machine/manageiq
against OpenStack Stein release.
Related: theopenlab/openlab#231
> Support backends OpenStack Stein

- zuul.d/pipelines.yaml
Add a pipeline to trigger acceptance tests against
OpenStack Stein release when comment 'recheck stable/stein'
in pull request.
Related: theopenlab/openlab#231
> Add pipeline 'recheck stable/stein'

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml
Currently periodic logs are going to pr-logs directory in bucket vs periodic-4/16
> Change zuul.pipeline check

- playbooks/manageiq-providers-openstack-test-devstack/run.yaml
- playbooks/manageiq-providers-openstack-test-public-clouds/run.yaml
Manageiq jobs are failed due to can't match the libssl
packages when wget for ubuntufailing bundler fixing. This
change uses wildcard to match the packages.
Closes: theopenlab/openlab#242
> Fix manageiq jobs failing

- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
"cloud-provider-openstack-acceptance-test-keystone-authentication-authorization"
failing since latest commit in k8s repo.  Failing with error "authorization-mode Webhook's authorization config file not passed" This commit is to fix the same.
Change in k8s repo: https://github.com/kubernetes/kubernetes/commit/f6bf44a205500eea65b97b36db3029e9e36e4676#diff-ed3df710e9af7cd30a185896a60897d9
same needs to be updated in job.
Close : https://github.com/theopenlab/openlab/issues/253
> Fix cloud-provider-openstack job failure

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
As per the issue
https://github.com/kubernetes/kubernetes/issues/77521#issuecomment-490108125,
issue seems to be happen only when KUBE_FASTBUILD=true.
Changing the same to check if it fixes the e2e job.
https://github.com/theopenlab/openlab/issues/254
> workaround to fix cpo e2e job

- playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/kf-tfbenchmarks.yaml.j2
- playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/kubeflow_tfbenchmarks.yaml
- playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/vc-tfbenchmarks.yaml.j2
- playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/volcano_tfbenchmarks.yaml
As we use VMs with CPUs resources to run the tensorflow benchmarks, it
will be very slow, we only care about the scheduling performances
between kubeflow and volcano, so we can reduce the bacthes of training
examples in the Tensorflow benchmarks to save time.
> Reduce the number of batches to be run in TFjobs

- playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/kubeflow_tfbenchmarks.yaml
- playbooks/tensorflow-volcano-kubeflow-integration-test-k8s/volcano_tfbenchmarks.yaml
After talking with mada, 2 TF jobs running in parallel can also present
the performance comparing, and will avoid the CI job timeout of kubeflow
job.
> Use 2 TF jobs for CI jobs testing of Volcano demo

- zuul.d/projects.yaml
Run bosh cpi test against openstack stable/stein
in periodic pipeline.
Closes: theopenlab/openlab#265
> Enable bosh cpi test against openstack stein periodic job

- zuul.d/projects.yaml
The OpenLab is a platform for Opensource SDKs/Tools,
disable the job for testing private cloud.
Closes: theopenlab/openlab#266
> Disable terraform-provider-huaweicloud-acceptance-test-fusioncloud

- playbooks/kind-integration-test-arm64/run.yaml
As suggested  in https://github.com/kubernetes-sigs/kind/issues/532
we downloaded KinD's dependancies from go111module as a walkaround,
thus the code is not in the original path, we add a soft link to
it and comment out some of previous code, we can restore it once  the issue has been fixed.
Related-Bug: theopenlab/openlab#269
> Add soft link for kind dir

- roles/clone-devstack-gate-to-workspace/tasks/main.yml
- roles/create-devstack-local-conf/tasks/main.yml
- zuul.d/jobs.yaml
1. The OpenStack official repo has been moved to `opendev.org`,
we should also follow it.
2. openstack-infra has been migrated to openstack repo.
Closes: theopenlab/openlab#284
> Correct the openstack git repo and openstack-infra

- playbooks/kind-integration-test-arm64/run.yaml
Add a walk-around for missing ``started`` time in
case k8s cluster failed to setup. Also copy full
cluster setup logs to logdir for better debuging.
> Fix post_failure for kind

- playbooks/manageiq-providers-openstack-test-devstack/run.yaml
An error occurred while installing dry-validation (0.13.1),
and Bundler cannot continue for manageiq jobs.
Change to use ruby 2.4.0 to fix this bug.
Related-Bug: theopenlab/openlab#246
> Use ruby 2.4.0 instead for manageiq jobs

- roles/create-devstack-local-conf/tasks/main.yml
Service q-lbaasv2 is required if enable octavia when
installing devstack of mitaka branch.
https://github.com/openstack/octavia/blob/mitaka-eol/devstack/plugin.sh#L253-L255
Closes: theopenlab/openlab#289
> Enable service q-lbaasv2 when octavia enabled for mitaka

- playbooks/spark-integration-test-kubeadm-k8s/run.yaml
- roles/install-openjdk/defaults/main.yaml
- roles/install-openjdk/tasks/main.yaml
There is some unknown error that causes
spark job exit when installing openjdk8,
extract it to be a role and run it at
the begaining of the job to debug the
root causes.
> Extract install openjdk8 to a role

- roles/create-single-k8s-cluster-with-kubeadm/tasks/main.yml
The default pod network cidr is 192.168.0.0/16, it
perhaps conflict with the node ip, there are two ways
to fix this, change the cidr or change the network add on,
we choose the second one here.
Related-Bug: theopenlab/openlab#298
> Use flannel network add on when create k8s cluster

- roles/export-kind-gcp-account/tasks/main.yaml
Add no_log when setting gcp account to avoid password leak since the prblem in
post job has been solved.
> Add no_log when setting gcp account

- playbooks/manageiq-providers-openstack-test-devstack/run.yaml
The `bundle exec rake db:setup` command doesn't work now, and now change to `bundle exec rake evm:db:reset db:seed` and `bundle exec rake test:vmdb:setup` to reset and setup test db.
This patch also skip the vcr test, because the vcr test does not working well.
Close: https://github.com/theopenlab/openlab/issues/246
> Fix ManageIQ job

- roles/config-packer/tasks/main.yaml
This fix the wrong platform and ARCH name from 'uname -a', as we use the ubuntu and X86 image, so we force to make packer job use linux_amd64 packer, and copy it into the right place.
Close: theopenlab/openlab#247
> Fix packer-master-functional-devstack for changing "make bin" to "make dev"

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
magnum-auto-healer binary was added to cloud-provider-openstack recently, we need to build and upload its image to dockerhub as well.
> Upload magnum-auto-healer image to k8scloudprovider dockerhub

- roles/create-devstack-local-conf/tasks/main.yml
When install mitaka devstack, the service q-lbaas is
enabled default, but if octavia enabled, it requires
the service q-lbaasv2. So let's disable q-lbaas and
enable q-lbaasv2 to make sure Neutron can be started.
Closes: theopenlab/openlab#304
> Disable q-lbaas for mitaka devstack enabled octavia

- zuul.d/jobs.yaml
Release 1.13 of Kubernetes supports Go 1.12
https://github.com/kubernetes/kubernetes/blob/release-1.13/Godeps/Godeps.json#L3
> Update Go version for 1.13 conformance job

- roles/config-packer/tasks/main.yaml
The "make bin" command has been broken(fixed but not released)
The "make dev" command can only work on master branch
Closes: #theopenlab/openlab#306
> Use "go install" instead of "make" command for compiling packer

- roles/config-docker-machine/tasks/main.yaml
- roles/install-docker-ce/tasks/main.yml
- roles/install-docker/defaults/main.yaml
- roles/install-docker/tasks/main.yml
- zuul.d/jobs.yaml
The new role "install-docker" install docker-ce by using get.docker.com
script, it support multiple OS and arch, and keep consistent docker-ce
version, mark role "install-docker-ce" as deprecated, and apply new role
in all of docker-machine jobs. Update tag of docker-machine job from
latest-release to 18.06 in order to avoid confusions.
Related-Bug: theopenlab/openlab#308
> Add new role "install-docker"

- playbooks/helm-integration-test-kubeadm-k8s/run.yaml
- playbooks/kind-integration-test-arm64/run.yaml
- playbooks/spark-integration-test-minikube-k8s/run.yaml
- roles/create-multinodes-k8s-cluster-with-kubeadm/tasks/main.yaml
- roles/create-single-k8s-cluster-with-kubeadm/tasks/main.yml
- roles/install-k8s/tasks/main.yaml
- zuul.d/jobs.yaml
Make all of OpenLab jobs to use new role "install-docker" to
install and config docker-ce, update tags of related jobs
to specific docker version and remove all of "latest-release" define.
Closes: theopenlab/openlab#308
> Apply role "install-docker" to all of jobs

- playbooks/kind-integration-test-arm64/run.yaml
> Refactor KinD on ARM job

- zuul.d/pipelines.yaml
In this patch, we change the pipeline start section, that means when start to running job, the status url will be set to `https://status.openlabtesting.org/status` to show the running job.
Once the job is finished, the job would set back to original status URL to show the test result.
Related: https://github.com/theopenlab/openlab/issues/311
> Set start detail url to status main page

- playbooks/docker-machine-functional-devstack/run.yaml
- playbooks/spark-integration-test-minikube-k8s/run.yaml
- roles/config-docker-machine/tasks/main.yaml
- roles/install-docker/tasks/main.yml
1. systemctl is not available on Ubuntu 14.04, so using
"service docker restart" as a workaround.
2. change option "--r" position in spark-inegration-test-minikube-k8s
job to avoid "--r" is bypassed to mvn.
3. change the importing order of roles in docker-machine job to make sure the
docker installation won't clean the iptables rules added by devstack
Related-Bug: theopenlab/openlab#308
Related-Bug: theopenlab/openlab#310
Co-authored-by: liu-sheng <liusheng2048@gmail.com>
> Fix install-docker role

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Clean up the pre-built k8s binaries output folder which is generated in`install-k8s` role. Otherwise `kubetest` will fail due to some unknown conflicts.
Related-Bug: theopenlab/openlab#317
> Fix cloud-provider-openstack CI error

- roles/install-openjdk/tasks/main.yaml
If using `no_log` and `register` together, the `regitster` one will be empty.
> Do not use `no_log` and `register` together

- zuul.d/jobs.yaml
- zuul.d/nodesets.yaml
Put all nodeset define together so that Openlab operator can
check all nodepool labels in zuul file nodesets.yaml.
Related-Bug: theopenlab/openlab#256
> Move k8s tensorflow nodeset into nodesets.yaml

- roles/create-devstack-local-conf/tasks/main.yml
Now we enable barbican only if 'octavia' or 'lbaas'
enabled, to make sure users can enable barbican
individually.
Close: theopenlab/openlab#320
> Enable barbican plugin individually

- zuul.d/jobs.yaml
- zuul.d/nodesets.yaml
- zuul.d/secrets.yaml
We want to move cpo related jobs from vexxhost to citynetwork. Before moving, we should test the jobs works well on citynetwork. This PR add temp jobs for testing. After testing well, we'll adopt the change to the offical jobs and remove the temp ones.
Related-Bug: theopenlab/openlab#321
> Add temp cpo jobs for test

- roles/export-cloud-openrc/tasks/main.yaml
we use project_domain_name instead of project_domain_id for citynetwork provider
> use project_domain_name

- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
There is a case that a network contains more than one subnet, in such case, we should select one from the list.
Related-Bug: #theopenlab/openlab#321
> Fix cpo lb job

- zuul.d/jobs.yaml
- zuul.d/nodesets.yaml
Now vexxhost provider is only used for arm and cpo lb jobs
Close: theopenlab/openlab#321
> Add vexxhost lb label

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml
- playbooks/kind-integration-test-arm64/post.yaml
k8s test-infra now use python3 by default[1]. Update related jobs to py3 as well.
[1]: https://github.com/kubernetes/test-infra/commit/7b4a98f8addfbc2d3236476ca378bf9f2d4b0b7c
> Use python3 for cpo test

- roles/prepare-workspace/tasks/main.yml
When update /etc/hosts file, it should has root permission.
> Add root permission for /etc/hosts

- roles/install-openjdk/defaults/main.yaml
- roles/install-openjdk/tasks/main.yaml
Now many project use scala, it's good to add a common role.Since scala depends on java, add the install step inner openjdk role. Users can install scala after openjdk with the var `with_scala`
> Add scala install step

- roles/install-openjdk/tasks/main.yaml
scala 2.11.0 -version return code is not 0 even there is no error.
Remove set -ex to make the job happy
> Fix scala 2.11.0 bug

- roles/install-openjdk/tasks/main.yaml
scala -version will raise on 2.11.0 even there is no error.
Ignore the error.
> Fix scala 2.11.0 version bug

- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Now we run integration tests of spark of v2.4.0
against v1.13.3 k8s, so to correct the job name.
Related-Bug: theopenlab/openlab#310
> Correct spark job name

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml
- playbooks/cloud-provider-openstack-test/pre.yaml
upload_e2e.py uses subprocess.check_out(...encoding...). The encoding parameter is added in python3.6, but the default version in ubuntu16.04 is python3.5.
Install and use python3.7 to fix the issue.
> Fix CPO job error

- roles/install-devstack/tasks/main.yml
Openstack requirements already update the requests version to 2.22.0,
but pypi only has this specific version for python27 python35 python36
and python37. And currently we use py34 in our jobs. So we need to
upgrade the python version from py34 to py35.
test success in allinone:
https://github.com/bzhaoopenstack/ansible/pull/1
> Fix ansible openstacksdk mitaka periodic job

- zuul.d/jobs.yaml
the `secrets` in the job definition is not inheritable. Create a new base job for lb related job on vexxhost provider.
> Fix CPO job openrc bug

- zuul.d/pipelines.yaml
Flink doesn't want ARM CI jobs run on every PR before it's stable enough. Add a comment only pipeline for this kind of requirement.
> Add a commnet only pipeline

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
explicitly on gomodule, due to the bug
https://github.com/kubernetes/test-infra/issues/14070
> Fix CPO conformance test 

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
use GOPROXY for faster downloading of go modules and fix conformance job.
> Use GOPROXY in CPO conformance tests

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
GOMODULE=ON causing problem in conformance tests v1.14 and v1.13,
disabled it for v1.14 and v1.13
> Fix conformance v1.14, v1.13

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
node port service tests are failing, due to blocked ports, setting the open port range
> Set NODE_PORT_RANGE Cloud provider openstack

- playbooks/spark-unit-test-arm64/run.yaml
- roles/install-maven/defaults/main.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Add periodic job to build and test spark on
aarch64 instance.
Related-Bug: theopenlab/openlab#316
Related-Bug: theopenlab/openlab#318
> Add job to build/test spark on arm64

- playbooks/spark-unit-test-arm64/run.yaml
The job will exit if we set -o option due to the
zinc error which we should ignore.
Related-Bug: theopenlab/openlab#316
> Don't set -o for spark arm64 job

- zuul.d/pipelines.yaml
- zuul.d/projects.yaml
For saving arm resources, we only run 1 time per day for ARM periodic testing.
> Split the periodic pipeline to a single period

- zuul.d/nodesets.yaml
Add a new nodeset for cpo multi node job, it includes 3 nodes. One for k8s master and the other two for k8s node.
Relate-bug: theopenlab/openlab#342
> Add new nodeset for cpo multi node job

- playbooks/spark-unchanged-branch-unit-test/run.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
This periodic test will test on theopenlab/spark, and on branch
test-branch20190909, which means the commits before the date. This is
for making sure our CI is good, the new issues come from the upstream.
> Introduce demo spark test

- playbooks/init-test/pre.yaml
- roles/prepare-workspace/tasks/main.yml
- Create workspace directory with zuul permission
- Keep the role of "prepare-workspace" as its name show
Closes: theopenlab/openlab#359
> Do not create root permission directory under /home/zuul

- playbooks/spark-unit-test-arm64/run.yaml
1. set -o pipefail
2. the permission of zuul/workspace is correct
after pr#645, use 'tee' instead of 'sudo tee'
for spark arm job
> Fix nits for spark arm job

- roles/install-k8s/tasks/main.yaml
hyperkube binary is removed from local-up-cluster.sh but still
used by at other places (golang.sh), so adding the same.
> Build hyperkube binary

- zuul.d/projects.yaml
The spark arm job fails always these days, seems
the performance of arm instance choosen is poor.
This changes the periodic time of spark job to utc0.
> [WIP]Change apache/spark arm job to periodic-0

- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
The recent [change ](https://github.com/kubernetes/kubernetes/commit/2550b31beb18e986aa89834302187288b3a6c96e)in k8s added the `AUTHORIZATION_WEBHOOK_CONFIG_FILE` and `AUTHENTICATION_WEBHOOK_CONFIG_FILE` options already. We don't need hack them now.
related: theopenlab/openlab#364
> Fix CPO keystone auth job

- playbooks/flink-end-to-end-test/post.yaml
lxml doesn't support ARM by default. Use Ubuntu packaged ones instead.
> Fix lxml ARM error

- playbooks/flink-end-to-end-test/post.yaml
copy module support copy remote dictionary only in ansible 2.8+. See: https://github.com/ansible/ansible/pull/43998
But zuul contains ansible < 2.8. So we should use cp command instead.
> Use cp command instead of copy module

- playbooks/flink-end-to-end-test/run_part1.yaml
- playbooks/flink-end-to-end-test/run_part2.yaml
- playbooks/flink-end-to-end-test/run_part3.yaml
The maven shaded plugin version error has been fixed in Flink already.
See: https://github.com/apache/flink/pull/9817
Remove the hacking task now.
> Remove maven shaded plugin hack

- playbooks/flink-end-to-end-test/run_part3.yaml
ARM VM performance seems poor. The default 10s for akka is not
enough. Try increase akka timeout to fix the job failure.
> Increase akka timeout

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- zuul.d/jobs.yaml
This PR fixes the conformance job failure, which is caused by unable to build kubetest
> Fix conformance jobs

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
This commit adds cpo e2e conformance job for 1.16 release and also removes
older releases than 1.14
> Update cpo e2e conformance jobs to run with latest release.

- zuul.d/jobs.yaml
This PR fixes the conformance job failure, which is caused by unable to build kubernetes:
```
make: Entering directory '/home/zuul/src/k8s.io/kubernetes'
make[1]: Entering directory '/home/zuul/src/k8s.io/kubernetes'
Detected go version: go version go1.12.1 linux/amd64.
Kubernetes requires go1.12.4 or greater.
Please install go1.12.4 or later.
!!! [1011 04:43:22] Call tree:
!!! [1011 04:43:22]  1: hack/run-in-gopath.sh:30 kube::golang::setup_env(...) 
Detected go version: go version go1.12.1 linux/amd64.
Kubernetes requires go1.12.4 or greater.
Please install go1.12.4 or later.
```
/cc @adisky @ramineni @huangtianhua
> Bump go version to 1.12.10

- zuul.d/jobs.yaml
Use tag instead of using branch for spark checkout, as branch-2.4 is not a protected branch anymore
> Use tag instead of using branch for spark checkout

- zuul.d/pipelines.yaml
This PR add a new pipeline. It's used for sending Flink test result to flink official mail list
> Add new pipeline for Flink mail trigger

- zuul.d/jobs.yaml
Use v2.4.4 for spark testing because v2.4.4 is the latest released stable version.
> Use v2.4.4 for spark testing

- roles/install-k8s/defaults/main.yaml
Latest k8s version require etcd version 3.3.17 or higher, This commit updates the same.
> Bump etcd version to 3.3.17

- zuul.d/projects.yaml
This changes:
1. remove spark periodic job of unchanged branch
2. disable periodic job spark-master-unit-test-hadoop-2.7-arm64,
this job now is triggered in community jenkins
3. disable hbase and hive arm test jobs
> Disable spark periodic jobs

- roles/create-multinodes-k8s-cluster-with-kubeadm/tasks/main.yaml
This change allows users of create-multinodes-k8s-cluster-with-kubeadm
to provide a kubeadm.yaml file over using command line flags of kubadm.
The default behavior is kept.
An example use-case for this: I currently work on a test case for
CSIMigration. For this I need to enable specific FeatureGates on the
controller-manager, and the kubelet.
> Extended multinode with kubeadm configuration

- roles/create-multinodes-k8s-cluster-with-kubeadm/tasks/main.yaml
Updated flannel to latest commit of the coreos repo. We need this update, because the
old one used deprecated resources that are removed in k8s 1.16.
With this change we still could test down to 1.10.
> flannel update in multinode to work with 1.16

- roles/create-devstack-local-conf/tasks/main.yml
Don't override enabled services when create devstack
local conf with 'manila' enabled.
Related-Bug: theopenlab/openlab#382
> Do not override enabled services

- roles/install-k8s/defaults/main.yaml
/cc @adisky 
relates to https://github.com/kubernetes/cloud-provider-openstack/pull/762
> Bump etcd version for OpenStack k8s cloud provider

- playbooks/helm-integration-test-kubeadm-k8s/run.yaml
Chart stable/postgresql won't delete the pvc after
delete the chart release, install and test the chart
separately to make sure other charts install success.
> Fix error of helm jobs

- zuul.d/jobs.yaml
This commit updates go version to 1.13.4 as minimum version
required by k8s.
> CPO: Update go version 1.13.4

- zuul.d/jobs.yaml
To the error below:
```
Detected go version: go version go1.12.4 linux/amd64.
Kubernetes requires go1.13.4 or greater.
Please install go1.13.4 or later.
```
/cc @adisky @ramineni @wangxiyuan @huangtianhua
> Bump go version for the latest k8s

- playbooks/labkeeper-allinone-deployment-test/run.yaml
ansible 2.9.0 doesn't work with openstack nodepool role.
Hardcode the ansible version to fix the issue.
> Fix labkeeper job failure

- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
This PR is to export kubeconfig as env variable which is required for e2e tests
> CPO: export kubeconfig as env variable for e2e test

- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
CPO keystone job is failing 
Root cause: kube-apiserver failed to start with error Error: invalid authorization config: unsupported webhook authorizer version "", supported versions are "v1", "v1beta1" . 
Explicitly pass the version while starting apiserver as per https://github.com/kubernetes/kubernetes/pull/84768
> CPO: Fix keystone job error

- playbooks/flink-end-to-end-test/e2e_tpcds.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
This patch add flink tpcds e2e test. And move the stable container
test to the mail queue.
> Add tpcds e2e test

- playbooks/flink-end-to-end-test/build_and_test_libraies_and_blink_planner.yaml
- playbooks/flink-end-to-end-test/build_and_test_misc.yaml
- playbooks/flink-end-to-end-test/e2e_tpcds.yaml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
This PR did:
1. Move tpcds test to offical
2. Add a new job for libraries and blink-planner
3. Add a new job for misc
4. Remove the hack in tpcds test which is merged into Flink Upstream already.
> Add new unit test for Flink

- zuul.d/jobs.yaml
- zuul.d/projects.yaml
This commit adds cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.17 job
> CPO: Add release-1.17 conformance job

- zuul.d/jobs.yaml
Devstack requires ubuntu 18.04 now.
Close-bug: theopenlab/openlab#419
> Use bionic for terraform job

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
Fixed two issues that didn't show up during local tests:
* used hard-coded path for kubectl
* `$(NODE_ID)` in heredoc needs to be escaped
> csi-manila job: fixed kubectl exec, escaped eval

- zuul.d/projects.yaml
The envoy and containerd project test case has been intergrated in CNCF.CI, we now we can remove the periodic job in openlab.
Note that the containerd PR triggered job is till running.
> Remove containerd and envoy periodic job

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
- playbooks/cloud-provider-openstack-multinode-csi-migration-test/run.yaml
Fixed bootstrap for of k8s-nodes. Somehow the ansible run captured
stderr and stdout combined, what caused a failure when bootstrappping
nodes.
Enabled junit output.
> Updated CSIMigration playbook to fix bootstrap

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
- zuul.d/pipelines.yaml
This commit updates migration test to install go on k8s master node
and run make on csi cinderplugin. This commit also adds the pipeline
to run the job when PR submitted.
> CPO: Fix migration test

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- zuul.d/jobs.yaml
Pipeline for CPO jobs seems to be changed, so latest images are
not getting pushed to docker registry. This commit updates the
pipeline in CPO jobs as well to fix the same.
This commit also fixes the periodic job failure of 
cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.16
by updating go version to 1.13.5 .
> CPO: update the pipeline for CPO jobs

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
migration job unable to push the images to registry
2020-01-21 05:05:15.520655 | TASK [push cluster-local-build of cinder-csi-plugin to local registry]
2020-01-21 04:05:16.167565 | k8s-master | The push refers to repository [localhost:32000/k8scloudprovider/cinder-csi-plugin]
2020-01-21 04:05:46.172091 | k8s-master | Get http://localhost:32000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
This PR tries to push using node ip and also clears the iptables before the docker push to resolve the error
> CPO: docker push using node ip

- roles/install-devstack/tasks/main.yml
It conflicts with devstack's pip install of httplib2.
Closes: https://github.com/theopenlab/openlab/issues/452
> Remove distutils httplib2 for devstack

- roles/install-devstack/tasks/main.yml
Currently apt waits for user input to remove `python3-httplib2`. This PR uses the apt module to uninstall the package.
Relates to: #785 
https://logs.openlabtesting.org/logs/19/919/8c9146151bd70313453c38328cc51dd64af61c0c/cloud-provider-openstack-acceptance-test-flexvolume-cinder/cloud-provider-openstack-acceptance-test-flexvolume-cinder/aae2d4a/job-output.txt.gz
```
2020-01-30 04:16:14.732684 | ubuntu-bionic | The following packages will be REMOVED:
2020-01-30 04:16:14.734138 | ubuntu-bionic |   apport python3-apport python3-httplib2 ubuntu-server
2020-01-30 04:16:14.742028 | ubuntu-bionic | 0 upgraded, 0 newly installed, 4 to remove and 3 not upgraded.
2020-01-30 04:16:14.742122 | ubuntu-bionic | After this operation, 1533 kB disk space will be freed.
2020-01-30 04:16:14.742209 | …
```
> install-devstack: Removed python3-httplib2 with apt module

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
We are still trying to debug the cluster for testing CSIMigration and struggle with containers not coming up. This PR lets collect logs and send it to a loki instance.
> Enable container logs for csi migration

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
Credentials were not set in tests, because the role `export-cloud-openrc` was missing.
> CPO: included export-cloud-openrc

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/run.yaml
This PR includes the role export-cloud-openrc in run.yaml as the credentials needed while running tests as well.
> CPO: Export cloud openrc in run.yaml

- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
- zuul.d/jobs.yaml
Basically, the workflow is:
- A new PR related to OCCM code is submitted.
- Openlab launches a VM and runs this zuul job.
- The OCCM image is built inside the VM and uploaded to docker hub.
- The zuul job updates image for OCCM running in an existing k8s
cluster on Catalyst Cloud.
- Zuul job executes a shell script as functional testing.
What are needed:
- An openrc file for Catalyst Cloud.
- The kubeconfig file for the existing k8s cluster.
- Put test-lb-service-catalyst-cloud.sh in the repo.
> Loadbalancer type of Service test for OCCM

- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
- zuul.d/jobs.yaml
- Install golang 1.13
- Use ubuntu-bionic nodeset.
- Use catalyst_credentials
- Pause the ansible playbook for debugging purpose, the pause task will
be removed afterwards
> Fix job cloud-provider-openstack-acceptance-test-lb-octavia

- zuul.d/jobs.yaml
Fixes the error:
```
The task includes an option with an undefined variable. The error was: 'dockerhub' is undefined
```
> Add dockerhub secret for occ-test-lb-octavia

- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
Building the occm image needs GOPATH, otherwise the error `make: go: Command not found` is raised.
> Use environment when building the occm image

- playbooks/flink-end-to-end-test/build_and_test_kafka_gelly_and_connectors.yaml
- playbooks/flink-end-to-end-test/build_and_test_misc.yaml
elasticsearch2 is removed from Flink already.
> Drop elasticsearch2

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
Using the ``admin`` user and project allows false-positive test results if the code being tested uses OpenStack APIs that are not allowed for non-administrators, so use the regular ``demo`` user and project set up by devstack instead.
> Use ``demo`` user/project for csi-manila-secrets

- playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml
Sometimes from the log, I can see the following:
```
+ /home/zuul/src/k8s.io/kubernetes/cluster/kubectl.sh describe pods web
Name:         web
Namespace:    default
Priority:     0
Node:         ubuntu-xenial-citynetwork-citynetwork-openlab-0000121863/192.168.0.12
Start Time:   Wed, 04 Mar 2020 21:55:34 +0000
Labels:       <none>
Annotations:  Status:  Running
```
which leads to job failure.
This patch fixes the way to get the pod status.
> [CPO] Fix the CI job k8s-cinder

- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
Due to [1], we need to update this job to use new way to build images.
[1] https://github.com/kubernetes/cloud-provider-openstack/pull/910
> Fix cloud-provider-openstack-e2e-test-csi-cinder job

- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
This commit dumps to the container logs of cinder csi e2e tests of cloud-provider-openstack
> CPO: Dump container logs for e2e csi cinder

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-flexvolume-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-k8s-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-manila-provisioner/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-standalone-cinder/run.yaml
- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
Since we changed our makefile in kubernetes/cloud-provider-openstack [1]
We need to update tests accordingly.
This also correct [2] to use consist image names as previously have.
(So we still will have one same old docker image name)
[1] https://github.com/kubernetes/cloud-provider-openstack/pull/910
[2] https://github.com/theopenlab/openlab-zuul-jobs/commit/95ca894d4ffa44a4f6a8389eb317003cbe0d3c5c
> Adopt new make targets from OpenStack cloud provider

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
This PR forces Helm to deploy CSI Manila with `k8scloudprovider/manila-csi-plugin:latest` image.
To be merged after https://github.com/theopenlab/openlab-zuul-jobs/pull/821
/cc @tombarron @gouthampacha
> [CPO] Override image repository and tag for CSI Manila to always use the latest build

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
This is targeting recent failure caused by https://github.com/kubernetes/cloud-provider-openstack/pull/910
This also related to https://github.com/kubernetes/cloud-provider-openstack/pull/967
This allow us to run tests in local without push any manifest.
Current design for multi-arch will generate image without architecture
in name with pushing image manifest.
This change directly tag image in tests so we can test image locally
without push anything up.
> Allow tag image in test to avoid push image manifest

- playbooks/gpdb-installcheck-world-tests-on-arm64/run.yaml
As zuul directory is too long during test. So hard core to git clone the repo into /home/zuul/gpdb
> Fix the directory too long issue for gpdb

- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
Add VERSION variable to cloud-provider-openstack-e2e-test-csi-cinder
Which was missing from [1].
[1] https://github.com/theopenlab/openlab-zuul-jobs/pull/821
> [CPO] Add missing VERSION variable

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/run.yaml
So the Kubernetes e2e testsuite knows that our plugin is migrated.
> CSIMigration: Renamed migratedPlugin in testsuite

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
Since [1] merged, we can remove extra docker logins and no_log tags.
[1] https://github.com/kubernetes/cloud-provider-openstack/pull/967
> [CPO] fix perodic jobs: remove extra docker login

- playbooks/gpdb-installcheck-world-tests-on-arm64/run.yaml
dtm_recovery_on_standby test lacks rsync binary.
> Try to fix dtm_recovery_on_standby

- playbooks/cloud-provider-openstack-unittest/run.yaml
To fix the error `note: module requires Go 1.13`, see https://logs.openlabtesting.org/logs/91/991/d7f000b8cc6765485abfa11d1213f1604122d724/cloud-provider-openstack-unittest/cloud-provider-openstack-unittest/62739dc/job-output.txt.gz
> [CPO] Pin golang version to 1.13.4

- playbooks/cluster-api-provider-openstack-conformance/post.yaml
- playbooks/cluster-api-provider-openstack-conformance/run.yaml
- zuul.d/jobs.yaml
@wangxiyuan Maybe you can already take a look. I still have to debug the job in the CAPO repo for a bit and then have to merge the e2e-conformance script on master first
See also issue: https://github.com/theopenlab/openlab/issues/141
> add CAPO conformance test

- playbooks/cloud-provider-openstack-unittest/run.yaml
Fix the job failure of cloud-provider-openstack-unittest, we don't need to install glide any more:
```
2020-03-27 05:12:31.316559 | ubuntu-xenial-citynetwork | + go get -u github.com/Masterminds/glide
2020-03-27 05:12:36.704129 | ubuntu-xenial-citynetwork | go: finding github.com/Masterminds/glide v0.13.3
2020-03-27 05:12:36.808223 | ubuntu-xenial-citynetwork | go: downloading github.com/Masterminds/glide v0.13.3
2020-03-27 05:12:37.329723 | ubuntu-xenial-citynetwork | go: extracting github.com/Masterminds/glide v0.13.3
2020-03-27 05:12:37.521093 | ubuntu-xenial-citynetwork | go: downloading gopkg.in/yaml.v2 v2.2.7
2020-03-27 05:12:37.532296 | ubuntu-xenial-citynetwork | go: downloading github.com/mitchellh/go-homedir v1.1.0
2020-03-27 05:12:37.568332 | ubuntu-xenial-citynetwork | go: …
```
> [CPO] Remove glide module installation

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
From Kubernetes v1.18.0 on, the topology support and e2e testing is
extended. Therefor this commit also deploys
openstack-cloud-controller-manager to get nodes labeled with openstack
availability zone and region.
I needed to move the generation of the cloud-config secret up, so that occm
has access during its deployment, so that nodes can be labeled
appropriately, and a NoSchedule taint is removed.
> OCCM: deploy occm for topology testing in v1.18.0

- roles/install-k8s/defaults/main.yaml
latest k8s needs 3.4.7 version. updating the same.
> CPO: Update etcd version

- playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml
- zuul.d/jobs.yaml
Set 300m timeout for test run in
playbooks/terraform-provider-openstack-acceptance-test-lbaas/run.yaml.
Reference: https://github.com/theopenlab/openlab/issues/525
> Set higher openstack-acceptance-test-lbaas timeout

- zuul.d/pipelines.yaml
- zuul.d/projects.yaml
This changes:
1. set utc 6:00 to run kudu periodic job
2. sent result to dev@kudu.apache.org on failures
> Configure kudu periodic job

- zuul.d/jobs.yaml
This PR updates go version to 1.14.4 for all CPO jobs.
> [CPO] Update go version to 1.14.4

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
https://github.com/kubernetes/cloud-provider-openstack/pull/1110 moves the helm chart for manila-csi-plugin to `charts` directory. This PR reflects this change.
cc @strigazi
> manila-csi-plugin: helm chart was moved to charts/

- zuul.d/jobs.yaml
This commit removes post run for e2e conformance , as its been removed.
> [CPO] Remove post run for e2e conformance

- playbooks/tensorflow-arm-build/run.yaml
The upstream issue is
https://github.com/tensorflow/tensorflow/issues/38477
So we have only to downgrade the tensorflow_datasets version from the default 3.2.1 to 3.1.0.
Once the upstream issue is resolved. Will remove this limitation.
> Fix master error during verify the whl with MNIST test

- playbooks/gpdb-installcheck-world-tests-on-arm64/run.yaml
The upstream issue https://github.com/giampaolo/psutil/issues/1268
Downgrade the psutil from 5.7.2 to 5.7.0 during testing when using py27.
> Fix setup server error in gpdb with no module "psutil" error

- playbooks/tensorflow-arm-build/run.yaml
- playbooks/tensorflow-arm-build/run_release.yaml
- zuul.d/jobs.yaml
- zuul.d/pipelines.yaml
- zuul.d/projects.yaml
Add new pipeline for release CI.
Suport py35,py36,py37,py38 whl packages build.
Refactor the orig nightly build for fit all cases.
resolving-issues: https://github.com/theopenlab/openlab/issues/560 https://github.com/theopenlab/openlab/issues/559
> Enable TF release CI for tf 2.1.0 and 1.15.3 stable branches

- zuul.d/pipelines.yaml
Kudu community has added a builds@kudu.apache.org mailing list specific
for CI notifications, now the mailing list is OK to use, let change our
Kudu job.
> Change the Kudu CI notification email address

- playbooks/gpdb-installcheck-world-tests-on-arm64/run.yaml
In test env, I found it will inject the interaction during demo cluster
startup. So for forbid this issue, add the localhost signal into
known_hosts when the cluster setup the segment using hostname.
> Fix gpdb ci test env

- zuul.d/projects.yaml
Pause tf 1.15 and 2.1.0 release Build for not change the upstream aarch64 download url so frequently.
Will change to manually enable build per 2 months. As zuul doesn't know correct the time definition of the related pipeline.
> Pause tf 1.15 and 2.1.0 release Build

- zuul.d/jobs.yaml
This commit updates go version of CPO jobs to 1.15.0
> [CPO] Update Go version to 1.15.0

- zuul.d/jobs.yaml
1.15.0 version key is not found , needs to be updated to 1.15 to get downloaded.
This commit fix the same.
> Fix go version to 1.15

- roles/install-k8s/defaults/main.yaml
Updates default etcd server to 3.4.9, which is default
version of k8s master
> [CPO]Update default etcd server to 3.4.9

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
This PR is related to https://github.com/theopenlab/openlab-zuul-jobs/pull/972#issuecomment-675431409
The k8s master etcd server version `3.4.9` is set as default in https://github.com/theopenlab/openlab-zuul-jobs/pull/972/commits/340c7a8a191a8177cac1e68a27c4ea24343f0c05
Therefore the overwrites are removed as part of this PR.
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
> [CPO] Remove etcd server overwrites 3.4.9

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
1.17 e2e conformance jobs seems to fail to incompatible target, this PR is to fix the same.
build-images target is not compatible with old releases. 
ref: https://logs.openlabtesting.org/logs/periodic-14/github.com/kubernetes/cloud-provider-openstack/release-1.17/cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.17/18e79d8/job-output.json.gz
> [CPO] Make e2e conformance compatible with old releases

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
As per the new code, we dont directly read from /var/lib/cloud/data
so, this part shouldnt be required.
This is with ref to failure : https://logs.openlabtesting.org/logs/80/1180/68a6e132902bde8c056a5ed1f4bc96b2f9c3d26e/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/02d96ee/job-output.json.gz
> [CPO] Update csi cinder job

- roles/install-k8s/defaults/main.yaml
Latest k8s version requires , etcd version 3.4.13, so updating the same.
https://logs.openlabtesting.org/logs/78/1178/219712789a23f596781f4493426effaeca3cc260/cloud-provider-openstack-acceptance-test-csi-cinder/cloud-provider-openstack-acceptance-test-csi-cinder/0c709f5/job-output.json.gz
> [CPO] update etcd version to 3.4.13

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
There seems to be a bug in latest K8s which breaks snapshotting for csi-snapshotter v1. This PR disables all tests related to snapshots until this issue is resolved.
xref https://github.com/kubernetes/cloud-provider-openstack/pull/1151#issuecomment-689656700
CC @wangxiyuan
> manila-csi-plugin: temporarily disable snapshot tests

- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Use terraform-provider-openstack/terraform-provider-openstack as a
project tag.
This project was migrated to the new repository because of the changes
in Hashicorp Terraform providers releasing process.
All providers are moving to https://registry.terraform.io and
terraform-providers Github organization is deprecated.
> Update terraform-provider-openstack repo link

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
CSI Manila is moving to external-snapshotter v2.1.1.
This fixes the issue due to which snapshot tests
had to be temporarily disabled in #1020
> manila-csi-plugin: reenabled snapshot tests

- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
Install CSI snapshotter in e2e tests , required to enable snapshot tests
> [CPO] Enable CSI Snapshotter in e2e tests

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Skip the following NodePort related conformance tests because of the security group settings in the cloud provider (citynetwork):
```
2020-10-20 16:07:51.116698 | k8s-master | [Fail] [sig-network] Services [It] should have session affinity work for NodePort service [LinuxOnly] [Conformance]
2020-10-20 16:07:51.116731 | k8s-master | /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3511
2020-10-20 16:07:51.116766 | k8s-master |
2020-10-20 16:07:51.116854 | k8s-master | [Fail] [sig-network] Services [It] should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance]
2020-10-20 16:07:51.116913 | k8s-master | /workspace/anago-v1.19.3-rc.0.69+37babbd0e76c11/src/k8s.io/kubernetes …
```
> [CPO] Skip more NodePort related conformance tests

- zuul.d/jobs.yaml
Add `go_version: '1.14'` to Terraform jobs since it's the version used by
Hashicorp Terraform SDK.
Some new Go features like `errors.As` and other don't work wild old
versions but they're used in Terraform SDK.
For https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1092
> Use Go version 1.14 for OpenStack Terraform jobs

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Seeing occasional interrupts in conformance jobs resulting in failure.
This PR increases the timeout  and explicitly set the disable-log-dump=false
> CPO: Increase timeout for e2e conformance tests

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
e2e conformance is failing during dumping of cluster logs after the tests passed. To be able to debug adding more verbose and also giving explicitly write permission to dir to make sure permissions is not an issue.
> CPO: Add more verbose to e2e conformance test

- playbooks/impala-build-test-arm64/run.yaml
Impala job failed when build kudu, so keep related logs to check.
> Put native-toolchain check logs to test_results directory

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
Dumping logs on master is failing due to unset variables of KUBE_MASTER 
2020-11-19 16:13:12.858162 | k8s-master | Dumping logs from master locally to '/home/zuul/workspace/logs/kubernetes'
2020-11-19 16:13:12.858754 | k8s-master | KUBE_MASTER_IP:
2020-11-19 16:13:12.858800 | k8s-master | KUBE_MASTER:
2020-11-19 16:13:12.859247 | k8s-master | ./cluster/log-dump/log-dump.sh: line 343: MASTER_NAME: unbound variable
https://logs.openlabtesting.org/logs/periodic-14/github.com/kubernetes/cloud-provider-openstack/master/cloud-provider-openstack-acceptance-test-e2e-conformance/0828ff0/job-output.txt.gz
This PR sets the env variables to master ip.
> CPO: Set required env variables in conformance test

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
This PR sets the MASTER_NAME explicitly because of error
2020-11-19 16:13:12.859247 | k8s-master | ./cluster/log-dump/log-dump.sh: line 343: MASTER_NAME: unbound variable
> CPO: Set MASTER_NAME as well explicitly.

- playbooks/kafka-build-test-arm64/run.yaml
1.Use zuul instead of root to run the testcase.
2.Delete the step of install openjdk, because the openjdk is already
exists.
> Modify the zuul job for kafka arm ci

- zuul.d/jobs.yaml
Resolve issue: https://github.com/theopenlab/openlab/issues/667
Due to `cloud-provider-openstack-acceptance-test-csi-manila` and `cloud-provider-openstack-acceptance-test-keystone-authentication-authorization` are already ubuntu bionic images.
So this time, upgrade `cloud-provider-openstack-acceptance-test-csi-cinder` and `cloud-provider-openstack-e2e-test-csi-cinder` testnodes from 1604 to 1804.
> Upgrade CPO cinder test jobs image from xenial to bionic

- zuul.d/jobs.yaml
- zuul.d/nodesets.yaml
upgrade  `cloud-provider-openstack-acceptance-test-csi-cinder`, `cloud-provider-openstack-e2e-test-csi-cinder`, `cloud-provider-openstack-acceptance-test-csi-manila` and `cloud-provider-openstack-acceptance-test-keystone-authentication-authorization` from ubuntu 1804 to 2004
Affected issue: https://github.com/theopenlab/openlab/issues/667
> Upgrade ubuntu focal x86 image for CPO

- roles/install-devstack/tasks/main.yml
Assuming we don't want openrc contents to be logged, echoing it should be no_log as well.
> Add missing no-log to install-devstack

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
The multi-node k8s cluster installation is still failed because:
```
2021-02-03 01:34:35.626590 | k8s-node-2 | 	[WARNING Hostname]: hostname "k8s-node-2" could not be reached
2021-02-03 01:34:35.626691 | k8s-node-2 | 	[WARNING Hostname]: hostname "k8s-node-2": lookup k8s-node-2 on 127.0.0.1:53: no such host
```
This patch makes sure the hostname is present in /etc/hosts.
> [CPO] Include host name in /etc/hosts

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- roles/create-multinodes-k8s-cluster-with-kubeadm/tasks/main.yaml
The PR (and the previous several ones) fixes the job
cloud-provider-openstack-acceptance-test-e2e-conformance by:
1. Getting hostname from Nova metadata service (default is ubuntu)
2. Changing hostname for the nodes
> [CPO] Fix the k8s cluster installation for cpo e2e conformance test

- roles/install-devstack/tasks/main.yml
This reverts commit 30ffe4b62a41037d08491aaccf7c39f2b1b2e1a7.
Terraform and gophercloud jobs are failing on this task[1], and the
no_log hides the actual error.  We don't really need a no_log
here since this openrc is for a throwaway test cloud -- the password
that is being hidden is the literal string "password" so there's
no secret info.
[1] https://github.com/theopenlab/openlab/issues/681
> Revert "Add missing no-log to install-devstack (#1062)"

- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
This also works around the hostname == ubuntu issue
In this case, /etc/hosts is also set up with all nodes just in case.
> [cinder-csimigration] added hostname and hosts

- playbooks/cloud-provider-openstack-acceptance-test-csi-cinder/run.yaml
- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/run.yaml
- playbooks/cloud-provider-openstack-multinode-csi-migration-test/pre.yaml
- roles/cloud-instance-hostname/tasks/main.yml
The error:
```
2021-02-07 11:28:36.785301 | TASK [Set hostname]
2021-02-07 11:28:37.671930 | k8s-node-1 | ERROR
2021-02-07 11:28:37.672460 | k8s-node-1 | {
2021-02-07 11:28:37.672606 | k8s-node-1 |   "msg": "Command failed rc=1, out=, err=Failed to create bus connection: No such file or directory\n"
2021-02-07 11:28:37.672692 | k8s-node-1 | }
2021-02-07 11:28:37.821684 | k8s-master | changed
2021-02-07 11:28:37.852968 | k8s-node-2 | changed
```
This PR moves the setting hostname function into a role.
> [CPO] Fix random failure when setting hostname

- roles/install-devstack/tasks/main.yml
Followup for the #1105
The `/opt/stack/new/devstack` file is available only within the `Install devstack on {{ global_env.OS_BRANCH }} branch` task. So we need to run sed inside the `devstack-gate/devstack-vm-gate-wrap.sh` script.
/assign @bzhaoopenstack @wangxiyuan @jeblair @emonty @lingxiankong
> [all]: Apply the pip constraints fix into the devstack-vm-gate-wrap.sh for Ubuntu Focal

- roles/install-devstack/tasks/main.yml
Another devstack python patch for Ubuntu Focal.
https://logs.openlabtesting.org/logs/84/1384/a2a6c42d771b29e4a364b78145904ec971e28072/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/a5331a1/logs/devstacklog.txt
```
2021-02-09 07:28:24.178 | Installing collected packages: requestsexceptions, munch, jsonpatch, jmespath, simplejson, openstacksdk, python-novaclient, python-cinderclient, osc-lib, python-openstackclient
2021-02-09 07:28:24.211 |   Attempting uninstall: jsonpatch
2021-02-09 07:28:24.212 |     Found existing installation: jsonpatch 1.22
2021-02-09 07:28:24.215 |     Uninstalling jsonpatch-1.22:
2021-02-09 07:28:24.245 |       Successfully uninstalled jsonpatch-1.22 …
```
> devstack task: ERROR: Cannot uninstall 'simplejson'

- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
Task: https://logs.openlabtesting.org/logs/84/1384/a2a6c42d771b29e4a364b78145904ec971e28072/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/bba5fc1/job-output.txt.gz
Error:
```
2021-02-09 08:58:40.811199 | ubuntu-focal | + apt-get install python-pip -y
2021-02-09 08:58:40.874150 | ubuntu-focal | Reading package lists...
2021-02-09 08:58:40.989569 | ubuntu-focal | Building dependency tree...
2021-02-09 08:58:40.990325 | ubuntu-focal | Reading state information...
2021-02-09 08:58:41.104459 | ubuntu-focal | E: Unable to locate package python-pip
2021-02-09 08:58:41.507686 | ubuntu-focal | ERROR
```
@wangxiyuan another fix for a package name
> [occm]: install python3-pip on focal

- roles/cloud-instance-hostname/tasks/main.yml
To fix:
```
2021-02-09 03:16:00.151186 | TASK [cloud-instance-hostname : Hostname | Set hostname]
2021-02-09 03:16:01.266271 | ubuntu-focal-citynetwork | ERROR
2021-02-09 03:16:01.266737 | ubuntu-focal-citynetwork | {
2021-02-09 03:16:01.266833 | ubuntu-focal-citynetwork |   "msg": "Command failed rc=1, out=, err=\u001b[0;1;31mUnknown operation ubuntu-focal-citynetwork-citynetwork-openlab-0000149931.\u001b[0m\n"
2021-02-09 03:16:01.266923 | ubuntu-focal-citynetwork | }
```
fixes #676
> Role cloud-instance-hostname: use systemd strategy to update hostname

- playbooks/cloud-provider-openstack-acceptance-test-e2e-conformance/post.yaml
- roles/export-gcp-account/tasks/main.yaml
- zuul.d/jobs.yaml
- zuul.d/secrets.yaml
We must replace our old bucket for test results by a new one. In this
PR, I added the new one additionally to the old one. When the new one
works as expected, I will remove the old one.
See: https://github.com/kubernetes/k8s.io/issues/1311
> [CPO] added new bucket

- playbooks/openlab-zuul-jobs-check/run.yaml
ansible-lint released version 5.0.0 what doesn't depend hard on ansible
any more. This PR installs ansible-lint[core] that does depend on
ansible.
See
https://github.com/ansible-community/ansible-lint/blob/650bc07fc4cbd05f9a98ea614589f907e965c61d/setup.cfg#L96
> Fixed installation of ansible-lint

- playbooks/openlab-zuul-jobs-check/run.yaml
The upstream ansible-lint has been upgraded to 5.0.1 version. And request the min version of ansible is 2.9.0 .
Openlab ansible runtime is 2.8.0 version, and all the jobs code with 2.8.0 syntax and format, so for ansible-lint, we can not upgrade to the latest version(5.0.1) directly.
And from my test, there are several obvious bugs towards the latest version, such as the `skip_list` doesn't work (expect is exchanging by ErrId), `tag_list` can only use the said newer names, and the initial check error in https://github.com/ansible-community/ansible-lint/blob/master/src/ansiblelint/_prerun.py#L39 (If we had a installed ansible version, the code would be failure.) . So I think the upstream software quality of ansible-lint is unavailable. We need to wait until the software is stable before …
> Fix openlab-check job

- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/run.yaml
This file will be uploaded after the run, and debugging failed runs will
be simpler for us.
> [cpo] Added e2e.log to e2e-test-csi-cinder

- zuul.d/jobs.yaml
1.16 go version required for CPO jobs. This PR updates the same.
> [CPO] Update go version to 1.16

- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/post.yaml
- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
When job A is running but the PR label was set by another job B, the job A should wait. However, if the waiting times out, job A shouldn't remove the label which was set by another job.
The Kubernetes resources should be cleaned up by the script itself in CPO repo.
> [CPO] Add signal file for PR label

- roles/cloud-instance-hostname/tasks/main.yml
The ansible role cloud-instance-hostname is quite unstable, it fails randomly with the following error:
```
2021-03-19 05:18:52.064876 | TASK [cloud-instance-hostname : Hostname | Set hostname]
2021-03-19 05:18:52.989693 | k8s-node-2 | ERROR
2021-03-19 05:18:52.990325 | k8s-node-2 | {
2021-03-19 05:18:52.990415 | k8s-node-2 |   "msg": "Command failed rc=1, out=, err=Failed to create bus connection: No such file or directory\n"
2021-03-19 05:18:52.990490 | k8s-node-2 | }
```
This PR fixes this issue by making sure dbus is installed before setting hostname by the `hostname` ansible module. Please see more discussion in https://github.com/ansible/ansible/issues/25543 and https://github.com/ansible/ansible/pull/55516
> Fix the ansible role cloud-instance-hostname

- playbooks/terraform-provider-openstack-acceptance-test-admin/run.yaml
- zuul.d/jobs.yaml
This commit creates a new job for the terraform-openstack-provider.
The job runs with admin credentials allowing to test scenarios that
require admin credentials.
This is a follow-up from https://github.com/theopenlab/openlab/issues/365 and relates to https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1211
> [TF-OS] Add new playbook for admin user

- playbooks/cloud-provider-openstack-e2e-test-csi-cinder/post.yaml
- roles/upload-testgrid/tasks/main.yml
We plan to include results of
cloud-provider-openstack-e2e-test-csi-cinder to be available in
testgrid. This PR uploads the results of the job so that testgrid can
visualize it.
The removed cleanup didn't cleanup anything real. So removed it.
> [cpo] upload results of csi e2e to testgrid

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
cpo/manila-csi-plugin is deployed using a helm chart. The playbook job was using helm2, which has been distontinued for some time now.
This PR makes it so that helm3 is installed and used instead.
> [cpo] manila-csi-plugin: install helm3

- playbooks/cloud-provider-openstack-acceptance-test-keystone-authentication-authorization/run.yaml
The main change in this PR is to install k3s (air-gap installed to avoid dependency on external docker images) instead of installing k8s using local-up-cluster.sh which is time-consuming and prone to error.
> [CPO] Refactor k8s-keystone-auth job

- playbooks/cloud-provider-openstack-acceptance-test-lb-octavia/run.yaml
Warning! I'm not able to test this locally! All I know for sure is that ansible-lint is happy with my changes.
I'm hoping this will give additional context to failures such as: https://logs.openlabtesting.org/logs/28/1528/39ea9b7a68866d6cb3ecec7431761b5ff0731aad/cloud-provider-openstack-acceptance-test-lb-octavia/cloud-provider-openstack-acceptance-test-lb-octavia/c5f119b/job-output.txt.gz
> Additional logging if OCCM fails to start

- playbooks/cloud-provider-openstack-cleanup-volumes/run.yaml
- roles/cleanup-cinder-csi-volumes/files/cleanup_volumes.py
- roles/cleanup-cinder-csi-volumes/tasks/main.yml
- zuul.d/jobs.yaml
- zuul.d/projects.yaml
Discussed in https://github.com/theopenlab/openlab/issues/746
This PR runs a job periodically to remove orphaned volumes created by
cinder csi. Post cleanup jobs directly on the real test jobs are not
robust enough in cases of e.g. timeouts or random crashes.
> cleanup for orphaned volumes of cinder csi

- playbooks/cloud-provider-openstack-acceptance-test-csi-manila/run.yaml
Snapshot controller v2 CRDs that the CI for manila-csi-plugin was installing are deprecated:
```
2021-06-08 03:07:56.344230 | ubuntu-focal | + for f in 'https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-2.1/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml' 'https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-2.1/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml' 'https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-2.1/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml' 'https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-2.1/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml' 'https://raw.githubusercontent.com/kubernetes-csi/external-snap …
```
> [CPO] manila-csi-plugin: bump snapshot controller to v4

- playbooks/cloud-provider-openstack-test-occm-e2e-conformance/run.yaml
- playbooks/cloud-provider-openstack-test-occm/run-1.19.yaml
- playbooks/cloud-provider-openstack-test-occm/run-1.20.yaml
- playbooks/cloud-provider-openstack-test-occm/run-1.21.yaml
- playbooks/cloud-provider-openstack-test-occm/run.yaml
- roles/install-k3s-vm/defaults/main.yaml
- roles/install-k3s-vm/tasks/main.yaml
- zuul.d/jobs.yaml
This change only affects cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.21
> [CPO] Use cloud-provider-openstack-test-occm as base job

- playbooks/openlab-zuul-jobs-check/run.yaml
We need the latest certificates on the host; which can be done by
upgrading the system.
Currently, zuul repo can't be cloned for that job because of this error:
```
fatal: unable to access 'https://opendev.org/zuul/zuul.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```
> openlab-zuul-jobs-check: upgrade the host before git clone zuul

- playbooks/openlab-zuul-jobs-check/run.yaml
Currently, zuul repo can't be cloned for that job because of this error:
```
fatal: unable to access 'https://opendev.org/zuul/zuul.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```
Let's ignore the SSL error for now.
> openlab-zuul-jobs-check: ignore SSL errors when cloning zuul

- roles/install-devstack/tasks/main.yml
It's rare but it can happen that devstack runs at the same time as a
crontab is triggered and runs APT to e.g. execute unattended upgrades of
the system.
Devstack would fail since APT isn't available.
This patch adds a workaround so it'll remove the crontabs before
deploying devstack.
> Add a workaround to avoid issues when devstack needs APT

- roles/install-devstack/tasks/main.yml
```
2021-11-02 16:54:58.373348 | TASK [install-devstack : Workaround to disable all root crontabs]
2021-11-02 08:55:00.133765 | ubuntu-focal | no crontab for root
2021-11-02 16:55:10.647948 | ubuntu-focal | ERROR
2021-11-02 16:55:10.648164 | ubuntu-focal | {
2021-11-02 16:55:10.648206 | ubuntu-focal |   "delta": "0:00:00.009216",
2021-11-02 16:55:10.648233 | ubuntu-focal |   "end": "2021-11-02 08:55:00.135359",
2021-11-02 16:55:10.648256 | ubuntu-focal |   "msg": "non-zero return code",
2021-11-02 16:55:10.648278 | ubuntu-focal |   "rc": 1,
2021-11-02 16:55:10.648299 | ubuntu-focal |   "start": "2021-11-02 08:55:00.126143"
2021-11-02 16:55:10.648319 | ubuntu-focal | }
```
This isn't working as expected, it'll need more work.
> Revert "Add a workaround to avoid issues when devstack needs APT"

- roles/install-devstack/defaults/main.yaml
- roles/install-devstack/tasks/main.yml
Adding `devstack_env` variable, when set it'll merge with Zuul
environment for running devstack. It can help when we want to customize
Devstack install.
> install-devstack: allow to extend ENV for devstack specifics

- roles/create-devstack-local-conf/defaults/main.yaml
- roles/create-devstack-local-conf/tasks/main.yml
- roles/create-devstack-local-conf/templates/devstack_overrides.conf.j2
- roles/install-devstack/defaults/main.yaml
- roles/install-devstack/tasks/main.yml
If devstack_env is set, we'll add the environment variables into the
local config for devstack. This will be useful for anyone who wants to
configure devstack for their needs, in the CI jobs.
This is backward compatible and disabled by default.
> Use devstack_env into create-devstack-local-conf role

- roles/create-devstack-local-conf/templates/devstack_overrides.conf.j2
This is bash environment, not YAML. Sorry for the typo.
> create-devstack-local-conf: fix a typo in the template

- roles/create-devstack-local-conf/tasks/main.yml
In my previous patch, I missed the fact that we set a default for
`devstack_env`. This patch will helps to make the playbook faster, if we
don't need to run the block. If the variable is an empty dic, we'll skip
the block as there is no need to configure overrides.
> create-devstack-local-conf: skip overrides if devstack_env is empty

- playbooks/init-test/pre.yaml
unattended-upgrades package in Ubuntu sets up a crontab that will
periodically upgrade the system and therefore run "apt".
We don't want that because it'll lock apt so things like devstack will
fail since they won't be able to use apt.
Let's just remove the package if installed, which is how other infras
are doing.
> Make sure we uninstall unattended-upgrades on Ubuntu

- roles/prefetch-amphora/README.md
- roles/prefetch-amphora/defaults/main.yaml
- roles/prefetch-amphora/tasks/main.yaml
Instead of building Amphora, allow to download it from a place (default
is RDO), into a specific directory.
This will save time for some jobs where Octavia devstack plugin builds
the Amphora image.
> Add a role to prefetch Amphora from RDO server

- roles/create-devstack-local-conf/tasks/main.yml
Allow to deploy neutron-dynamic-routing in devstack with defaults (BGP
on single node).
> Add support for neutron-dynamic-routing

- roles/create-devstack-local-conf/tasks/main.yml
Allows enable neutron-vpnaas with default values by adding `vpnaas` to
`enable_services`.
https://docs.openstack.org/neutron-vpnaas/latest/contributor/devstack.html
> Add support for vpnaas

- roles/create-devstack-local-conf/tasks/main.yml
Allows enable magnum with default values by adding `magnum` to
`enable_services`.
https://opendev.org/openstack/magnum/src/branch/master/devstack
> Add support for magnum

- roles/create-devstack-local-conf/tasks/main.yml
We were mistakenly setting the checkout branch to master.
> Do not force master branch for magnum
